### ISSUE TITLE
Add ability to detect if in a function or class to limit test to scope.

### ISSUE THREAD

**Issue by roni-estein** [pestphp/pest-intellij#10]
Love this plugin idea, I hope there is a way to make it happen. I'm not sure if it's just me, but I never use the IDE when using phpstorm, I simply run configure the test runner, and part of what it tests is either the whole project from the IDE, the class if you are outside a function declaration or that function if you are on or in the function declaration.
<img width="620" alt="Screen Shot 2020-06-30 at 10 25 00 PM" src="https://user-images.githubusercontent.com/8517475/86199948-15116d80-bb21-11ea-94b2-7bec24c44cc2.png">

**Comment by olivernybroe** [comment]
That should be possible yep, and definitely something that should and will be added.

Right now for me at least, the highest priority will be #6 and #5. But this one is pretty closely related to #6. 

What you can do so far is running the whole test suite or run a specific file.

**Comment by olivernybroe** [comment]
This partially works now. 

However as we still cannot run a single test, running it in a function scope is the same as file scope.

**Comment by olivernybroe** [comment]
This works now it the latest version 👍

**Comment by roni-estein** [comment]
Thanks, so excited to try this out today!

**Comment by olivernybroe** [comment]
@roni-estein Awesome. Don't hesitate with any feedback, helps a lot to figure out what to work on and testing it out. 🎆

**Comment by roni-estein** [comment]
Hey Oliver,
So far it seems to act as before. Here are the steps I've taken:
1. upgraded my EAP phpstorm 2020.2 to use pestphp-plugin 2.0
2. Fresh Laravel Install
3. Install pest
4. upgraded phpunit and collision to ^9.0 and ^5.0 respoectively.
5. removed the contents of the default feature test and replaced it with:

```php
<?php

it('lives')->assertTrue(true);
```
hovering over the test and using my shortcut "CMD + t" gives the following 
<img width="672" alt="Screen Shot 2020-07-15 at 9 49 47 AM" src="https://user-images.githubusercontent.com/8517475/87559944-894f2380-c680-11ea-8538-f3be2aa3727c.png">


test the old method: opening up unit tests and doing the same thing works fine as expected.
<img width="872" alt="Screen Shot 2020-07-15 at 9 52 31 AM" src="https://user-images.githubusercontent.com/8517475/87560384-febaf400-c680-11ea-83f3-2084d7b6a577.png">


Running Pest in command line works perfectly.
<img width="283" alt="Screen Shot 2020-07-15 at 9 54 08 AM" src="https://user-images.githubusercontent.com/8517475/87560509-24e09400-c681-11ea-920c-95b45804a45f.png">


If there is anything I can provide for you or if there is anything it seems like I missed in the description please let me know. Also, I noticed in 0.2 the "Pest" Icons are not on the test files. In 1.1 I believe they were.

**Comment by olivernybroe** [comment]
Hmm so multiple issues are raised here.
Let's go over them 😄 

So looks like the scoping is a bit off when using higher order tests. When using enclosures, the hotkey works, however when using higher order tests, it only works when pressing the hotkey while cursor is on `it` function call. A new issue has been opened for this #25 to follow.

Does it work for you when cursor is on `it` instead?


Regarding the icon missing on files, I am having a hard time reproducing this. 
The icon missing is also why the run configuration window doesn't have a run whole file scope as it sees it as.
Guess I have to debug some more to see if I can reproduce that.

**Comment by olivernybroe** [comment]
@roni-estein GitHub is having some problems, so the action for publishing the next version doesn't work atm.

I have uploaded a build here, could you check if it solves your problems?
[pest-intellij-0.2.1-alpha.1.zip](https://github.com/pestphp/pest-intellij/files/4927023/pest-intellij-0.2.1-alpha.1.zip)

**Comment by roni-estein** [comment]
Hey I had a chance to try it out, it's the same as the 2.0 for me. So far. I had to use show package contents on a mac to get the plugins directory. I was surprised there was no pest-intellij directory there. After pasting it in there and restarting as well as trying to install it directly from disk, all results were all the same. If it works for you, perhaps we could arrange a DM on discord to debug this together.
