### ISSUE TITLE
Create an 'Run all' button to run all the tests in a file

### ISSUE THREAD

**Issue by nirajhinge** [pestphp/pest-intellij#109]
There is no button to run all the tests in a file in one go similar to a standard class based PHPUnit test. Currently to run all the tests in a file, we can do it either from the `cli` with `--filters` flag to run all the tests for a class or right click outside of the functions and Run the tests as follows:

<img width="583" alt="Screenshot 2021-03-10 at 07 53 07" src="https://user-images.githubusercontent.com/54309996/110595673-39c0e900-8176-11eb-8d7d-dc00cf1112e5.png">

Ideally we would have a button similar to the class based tests (the double arrow) to run all the tests in a file as below:

<img width="106" alt="Screenshot 2021-03-09 at 11 30 16" src="https://user-images.githubusercontent.com/54309996/110595681-3ded0680-8176-11eb-967a-ed4e1951a33c.png">

**Comment by olivernybroe** [comment]
So in PhpUnit they have the advantage that they can show this icon on the class, however in pest we don't have a class. Where should we show the icon then?

PhpStorm limits us to bind it to an element, so we can't just say first line of file.

**Comment by nirajhinge** [comment]
I would say the only place I can think of is the line where we declare `namespace` otherwise the only element I can think of is `<?php`.

**Comment by olivernybroe** [comment]
Hmm, php opening tag might work. 🤔 

`namespace` won't as it isn't required to have the namespace in there. 
Another possibility is to add two icons on the first test, but let's see if we can get it to work with opening tag first as I think that might be cleaner.

**Comment by nirajhinge** [comment]
yep the opening php tag should be fine in terms of visual cue.

**Comment by olivernybroe** [comment]
@nirajhinge I got the feature ready, can I get you to test it out?

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-0.4.3-EAP.5.zip](https://github.com/pestphp/pest-intellij/files/6146657/PEST.PHP-0.4.3-EAP.5.zip)

**Comment by nirajhinge** [comment]
@olivernybroe Just tried it and it is working as expected for me :)

**Comment by olivernybroe** [comment]
@nirajhinge Nice, thanks!
