### ISSUE TITLE
`Expectation.php` generated file has wrong methods

### ISSUE THREAD

**Issue by Lukasss93** [pestphp/pest-intellij#163]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.5
| Pest version     | 1.15
| IntelliJ version | PS-212.4746.100
| OS               | Windows 10

### Context
![image](https://user-images.githubusercontent.com/4071613/129381468-dff79e95-45a3-414b-90fe-4094039f93f1.png)

### Stacktrace
[stacktrace.txt](https://github.com/pestphp/pest-intellij/files/6983434/stacktrace.txt)

**Comment by olivernybroe** [comment]
Hmm, I don't think the bug you are getting and the wrong input in the generated file is actually related.

Did the `toEqualStub` method at some point have the `eol` parameter? 
Did you perhaps copy the file or rename it? (trying to think of what could cause this 😆)

**Comment by Lukasss93** [comment]
It looks like it's fixed itself. Maybe it was wrong phpstorm cache? I don't know.

**Comment by olivernybroe** [comment]
Hmm might be 🤔 But thanks for following up!
