### ISSUE TITLE
pest test does not recognise as a php test

### ISSUE THREAD

**Issue by eerison** [pestphp/pest-intellij#166]
I have a strange behaviour in my project, phpstorm think that pest tests are javascript tests 🤯 

<img width="778" alt="Screenshot 2021-08-14 at 12 53 05" src="https://user-images.githubusercontent.com/6358755/129444050-bc8de036-3e6b-463e-9f91-1864240d68b7.png">

I don't know why, but I have 2 projects that phpstorm works different:

- https://github.com/eerison/pest-plugin-api-platform -> works
- https://github.com/eerison/myprofile/tree/master -> does not work

it's my phpstorm version 
<img width="467" alt="Screenshot 2021-08-14 at 12 53 31" src="https://user-images.githubusercontent.com/6358755/129444063-7c619a05-1a30-4959-a952-40c59d225982.png">

**Comment by olivernybroe** [comment]
Hi, thanks for reporting this issue. 

From a quick glance it looks like you might have forgotten to setup your test framework, could you please verify for me that the test framework has been configured? 
https://github.com/pestphp/pest-intellij#configuration

**Comment by eerison** [comment]
Hi @olivernybroe, you were right, it was missing I configure the pest php

But it's not working yet

when I'm running by phpstorm I'm getting this error:

```
[docker-compose://[/Users/erison.silva/Projects/myprofile/docker-compose.yml]:php/]:php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter=/^P\\App\\tests\\Feature\\UserTest::it\scan\sget\suser\sresource\swithout\sany\suser\slog\sin(\swith\s\(.*\)(\s#\d+)?)?$/
Testing started at 13:53 ...
Creating myprofile_php_run ... 
Creating myprofile_php_run ... done
Pest 1.15.0

   Pest\Exceptions\ShouldNotHappen 

  
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Test file not found.
- PHP version: 8.0.7
- Operating system: Linux

  at /app/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕ 

      +3 vendor frames 
  4   /app/tests/Feature/UserTest.php:3
ERROR: 1

Process finished with exit code 1
```

when I run by terminal it works

```
root@9a3e4ea7fc58:/app# vendor/pestphp/pest/bin/pest   
Testing 

   PASS  Tests\Feature\UserTest
  ✓ it can get user resource without any user log in

  Tests:  1 passed
  Time:   3.49s
```

I'm not sure if it's a problem in pest repository.

**Comment by olivernybroe** [comment]
Hmm, so looking at the command there shouldn't really be anything wrong 🤔 
When you run in terminal manually is it also in that docker container?
And can you try locally running with `--configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php`?
