### ISSUE TITLE
Pest in PHPStorm

### ISSUE THREAD

**Issue by menjilx** [pestphp/pest-intellij#18]
Is this the "Pest" plugin?
![image](https://user-images.githubusercontent.com/14908836/87036610-af5a6b00-c21d-11ea-84f8-1b8e62611e92.png)

**Comment by adelf** [comment]
No. It isn’t. Please, use https://github.com/pestphp/pest-intellij#installation to install early version of this plugin.

**Comment by menjilx** [comment]
> No. It isn’t. Please, use https://github.com/pestphp/pest-intellij#installation to install early version of this plugin.

Thank you and we will check this.

**Comment by olivernybroe** [comment]
@menjilx No stable release has been made yet :) So you have to use the EAP version. 

Will tweet when a stable release is out 👍
