### ISSUE TITLE
uses()->in(...) should autocomplete directories

### ISSUE THREAD

**Issue by felixdorn** [pestphp/pest-intellij#190]
Hey! Thanks for your work on this, it's awesome!

This is just a QoL improvement, not a bug.

![Screenshot from 2021-09-23 10-40-37](https://user-images.githubusercontent.com/55788595/134478221-f698e3e3-b98e-435a-9075-d9c834e00a99.png)

Here a list of directory could be shown.

**Comment by olivernybroe** [comment]
Hi, thanks for suggesting an improvement!

I think it's a good idea and something we definitely should do 👍
