### ISSUE TITLE
Find test classes with dynamic folder structure

### ISSUE THREAD

**Issue by Shhu** [pestphp/pest-intellij#193]
I dont have the autocomplete to $this inside a pest test() when using modular architecture : 

With Pest
![](https://cdn.discordapp.com/attachments/710642595705126923/892707077137506314/unknown.png)

With Phpunit
![](https://cdn.discordapp.com/attachments/710642595705126923/892707229281710080/unknown.png)

In Pest.php
`uses(TestCase::class)->in('../app/Blog/Tests/Feature');`

Architecture
```
app
    Blog
        Tests
            Feature
                StoreArticleTest.php
tests
    Pest.php
    TestCase.php
```

Using windows WSL2, Php 8, Phpstorm 2021.2.1, Pest plugin 1.1.0

**Comment by olivernybroe** [comment]
I have created a new EAP which should add support for this 👍 
If you wanna try it out, you can install it from here

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.3.1-EAP.1.zip](https://github.com/pestphp/pest-intellij/files/7712959/PEST.PHP-1.3.1-EAP.1.zip)
