### ISSUE TITLE
vendor/Expectation.php autocompletion docblock generation has wrong typehint on default values

### ISSUE THREAD

**Issue by fabio-ivona** [pestphp/pest-intellij#198]
Hi @olivernybroe!

I've added a custom expectation in my laravel-expectations plugin, like this one

```php
expect()->extend('toBeAbleTo', function (string $ability, $arguments): Expectation {...});
```

and it generates a correct docblock in `vendor/Expectation.php`

`@method \Pest\Expectation toBeAbleTo(string $ability,  $arguments)`

but, as `toBeAbleTo` maps also laravel's `$user->can('ability', $model)` and `$user->can('ability')` is should have this signature:

```php
expect()->extend('toBeAbleTo', function (string $ability, array|mixed $arguments = []): Expectation {...});
```

because of pestphp requirements, I'm still (:cry:) bound to php7.3, so the best I can do is: 

```php
expect()->extend('toBeAbleTo', function (string $ability, $arguments = []): Expectation {...});
```

unfortunately this one generates a misleading dockblock:

`@method \Pest\Expectation toBeAbleTo(string $ability, array $arguments = [])`

it autocompletes like this:

![image](https://user-images.githubusercontent.com/8792274/136648696-0c5eeef8-2dfb-4bc4-8d3e-dbadf7dd9c9a.png)

and give this warning:

![image](https://user-images.githubusercontent.com/8792274/136648730-36f4893f-cdd0-4f98-a84b-4bbf29de46f8.png)

the best solution I can think of is to add a little docblock before the extend declaration:

```php
/*
 * Assert that the given User is authorized to do something
 *
 * @param array|mixed $arguments
 */
expect()->extend('toBeAbleTo', function (string $ability, $arguments = []): Expectation {...});
```

but it is not parsed (still? :smile: )

Let me know if you need more info!

PhpStorm version: 2021.2.2 
_Pest Plugin version: 1.2.0_

**Comment by olivernybroe** [comment]
Hey @fabio-ivona,

The issue here is that your docblock has to be on your function, not on the function call 👍 

So changing the code to the following works.
```
expect()->extend(
    'toBeAbleTo',
    /**
     * @param array|mixed $arguments
     */
    function (string $ability, $arguments = []): Expectation {
        return $this;
    }
);
```

**Comment by fabio-ivona** [comment]
TIL: docblock can be put inside a function 🤯

**Comment by olivernybroe** [comment]
@fabio-ivona your docblock is invalid 😉 
It needs two * for it to be a valid docblock 👍
