### ISSUE TITLE
Dynamic plugin

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#20]
Make sure that the plugin is dynamic, meaning it can be loaded without reloading the IDE.

https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html

**Comment by adelf** [comment]
Verify task of your CI says that plugin is dynamic :)
However something is wrong there... it can’t load php plugin to check compatibility...

**Comment by olivernybroe** [comment]
@adelf Yeah also saw that, it says no supported version of php plugin is available. 

But I think we need to update what versions it is testing on, it is running on `2019.3` but we don't support that version :)

**Comment by olivernybroe** [comment]
Got it fixed, it was because it didn't test on IU edition. 

It says it's dynamic 👍

**Comment by olivernybroe** [comment]
Just tested it out, the plugin is not dynamic because of `PhpTestFrameworkType` class crashes when loaded dynamic. 

Not something we can change, except for reporting it to IntelliJ and hope they will make that class dynamic 👍
