### ISSUE TITLE
A setting to turn on/off plugin functionality

### ISSUE THREAD

**Issue by adelf** [pestphp/pest-intellij#21]
It will save resources for projects without PEST. It's also possible to detect "pestphp/pest" in `composer.json` file after project opening...

**Comment by olivernybroe** [comment]
@adelf I think that makes sense to add.

Right now we actually have `PestUtil::isEnabled` which can be used. This method checks if a pest executable has been defined.

The executable is always defined per project and if that is set, then we know the user wanted to use pest in this project.

We can later on add that the executable is automatically set, based on composer.


WDYT?

**Comment by olivernybroe** [comment]
The method has now been moved to an extension method for project. `Project.isPestEnabled()`.

Still new to Kotlin 😄

**Comment by adelf** [comment]
> Still new to Kotlin 😄

I'm using it every day about 8 months and also still a newbie :)

```
PhpTestFrameworkSettingsManager
            .getInstance(this)
            .getConfigurations(PestFrameworkType.getInstance())
```

Seems, this configuration appears there because of `PestComposerConfig`. This `isEnabled` method will be called very often if we will use it everywhere. I hope it doesn't make any big calculations inside...

**Comment by olivernybroe** [comment]
@adelf Hmm good point. If it turns out to be slow, then we could add some sort of cache around it 👍
