### ISSUE TITLE
test only works when run all tests into the file

### ISSUE THREAD

**Issue by eerison** [pestphp/pest-intellij#211]
Hello, I'm trying to run my tests by phpstorm by it just work when I run all test in the file.

it works
<img width="1262" alt="Screenshot 2021-11-04 at 20 03 02" src="https://user-images.githubusercontent.com/6358755/140403734-d4a367f7-4ee0-48c0-89f6-c311712b0682.png">

```
[docker-compose://[/Users/erison.silva/Projects/myprofile/docker-compose.yml]:php/]:php /app/vendor/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php
Testing started at 20:02 ...

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Testing /app/tests/Feature/UserTest.php
  /app/tests/Feature/UserTest.php
  Tests\Feature\UserTest 
✓ it can get user collection resource without any user log in.
✓ it can get an user item resource without any user log in.
✓ can not register an user with invalid data.


Tests:  3 passed
Assertions:  12
Time:  6.8353131s

Process finished with exit code 0
```

it doesn't work

<img width="1157" alt="Screenshot 2021-11-04 at 20 06 14" src="https://user-images.githubusercontent.com/6358755/140403887-8aae17b0-373d-4737-8b77-2358430f2c05.png">

```
[docker-compose://[/Users/erison.silva/Projects/myprofile/docker-compose.yml]:php/]:php /app/vendor/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter=/^P\\App\\tests\\Feature\\UserTest::it\scan\sget\suser\scollection\sresource\swithout\sany\suser\slog\sin.(\swith\s\(.*\)(\s#\d+)?)?$/
Testing started at 20:06 ...

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Tests:  
Assertions:  0
Time:  0s

Process finished with exit code 0
```

any idea why?

**Comment by eerison** [comment]
<img width="1140" alt="Screenshot 2021-11-04 at 20 19 06" src="https://user-images.githubusercontent.com/6358755/140405626-7db5f79a-ca48-4617-b83b-c3a7e5969fee.png">

and if fail one test and I click in run just the fail tests, it's running all tests again

**Comment by olivernybroe** [comment]
Thank you for all the details, would you be able to share the tests as text so I can copy paste them and thest locally?

**Comment by eerison** [comment]
Hi @olivernybroe it's the pull request that I've checked: https://github.com/eerison/myprofile/pull/502/files

**Comment by eerison** [comment]
I'll post here some examples

```php
declare(strict_types=1);

use App\Entity\User;

it('can get user collection resource without any user log in.')
    ->get('/users')
    ->assertResponseIsSuccessful()
    ->expectResponseContent()
    ->json()
    ->toHaveKey('hydra:totalItems', 14)
    ->toMatchesResourceCollectionJsonSchema(User::class)
;
it('can get an user item resource without any user log in.')
    ->get('/users/1000')
    ->assertResponseIsSuccessful()
    ->expectResponseContent()
    ->toMatchesResourceItemJsonSchema(User::class)
    ->toMatchJsonSnapshot()
;
```

Note: `get`, `assertResponseIsSuccessful` and `expectResponseContent` comes from https://github.com/eerison/pest-plugin-api-platform

**Comment by olivernybroe** [comment]
Thanks :) I'll test it out when I find some time for it 👍

**Comment by olivernybroe** [comment]
@eerison I am having some troubles reproducing this 🤔 
![image](https://user-images.githubusercontent.com/5870441/141698608-d51fda0a-bb75-468e-a8cf-d76b5070c08b.png)

Have you done the configuration steps? Might have an impact
https://github.com/pestphp/pest-intellij#configuration

**Comment by eerison** [comment]
Hi @olivernybroe good morning :) 

Yes I have configured the steps in the documentation.

<img width="1004" alt="Screenshot 2021-11-15 at 08 40 02" src="https://user-images.githubusercontent.com/6358755/141741387-2f56dc48-e595-4cc8-b261-50f41631dbd8.png">

**Comment by eerison** [comment]
Hey @olivernybroe, let me know if it helps you.

> Do you have an unusual setup? 🤔
 - Maybe yes, I'm using Symfony then it could be a bit different.
 - Or maybe because it's into of api folder: https://github.com/eerison/myprofile/tree/master/api

> For example what is your directory setup?
it's my test directory
<img width="423" alt="Screenshot 2021-11-15 at 08 58 09" src="https://user-images.githubusercontent.com/6358755/141743733-52f42311-9b59-4d35-bd90-6a7551d26b41.png">

> When looking at the command it ran, the issue seems to be in the filter part.

Yeah I think the same, It's the only difference between those 2 commands

> would you be able to test if this filter works instead for you? 👀

Test that I used
```php
it('is a test.', function () {
   expect(true)->toBeTruthy();
});
```

it works

```
docker-compose run --rm -e APP_ENV=test php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php                                                      
Creating myprofile_php_run ... done

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Testing /app/tests/Feature/UserTest.php
  /app/tests/Feature/UserTest.php

##teamcity[testCount count='1' flowId='1']
##teamcity[testSuiteStarted name='/app/tests/Feature/UserTest.php' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='1']
  Tests\Feature\UserTest 

##teamcity[testSuiteStarted name='Tests\Feature\UserTest' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='1']
##teamcity[testStarted name='it is a test.' locationHint='pest_qn:///app/tests/Feature/UserTest.php::it is a test.' flowId='1']
##teamcity[testFinished name='it is a test.' duration='731' flowId='1']
✓ it is a test.


##teamcity[testSuiteFinished name='Tests\Feature\UserTest' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='1']


##teamcity[testSuiteFinished name='/app/tests/Feature/UserTest.php' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='1']
Tests:  1 passed
Assertions:  1
Time:  0.7307459s

```

It doesn't works
```
docker-compose run --rm -e APP_ENV=test php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter="/^P\\App\\tests\\Feature\\UserTest::it\sis\sa\stest.(\swith\s\(.*\)(\s#\d+)?)?$/"
Creating myprofile_php_run ... done

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Tests:  
Assertions:  0
Time:  0s
```

it doesn't work

```
docker-compose run --rm -e APP_ENV=test php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter="/^P\\tests\\Feature\\UserTest::it\sis\sa\stest.(\swith\s\(.*\)(\s#\d+)?)?$/"

Creating myprofile_php_run ... done


Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Tests:  
Assertions:  0
Time:  0s
```

> Last thing, what does your dev-autoload look like?

```json
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
```
https://github.com/eerison/myprofile/blob/master/api/composer.json#L73-L76

**Comment by eerison** [comment]
Hey @olivernybroe I did others tests and maybe it can help you more

```
php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter '/^P\\Feature\\UserTest::it(.*)$/'

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Tests:  
Assertions:  0
Time:  0s
```

```
php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter '/\\Feature\\UserTest::it(.*)$/'

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Testing /app/tests/Feature/UserTest.php
  /app/tests/Feature/UserTest.php

##teamcity[testCount count='1' flowId='200']
##teamcity[testSuiteStarted name='/app/tests/Feature/UserTest.php' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='200']
  Tests\Feature\UserTest 

##teamcity[testSuiteStarted name='Tests\Feature\UserTest' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='200']
##teamcity[testStarted name='it is a test myuniquetest.' locationHint='pest_qn:///app/tests/Feature/UserTest.php::it is a test myuniquetest.' flowId='200']
##teamcity[testFinished name='it is a test myuniquetest.' duration='719' flowId='200']
✓ it is a test myuniquetest.


##teamcity[testSuiteFinished name='Tests\Feature\UserTest' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='200']


##teamcity[testSuiteFinished name='/app/tests/Feature/UserTest.php' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='200']
Tests:  1 passed
Assertions:  1
Time:  0.7190661s
```

```
php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter '/\\tests\\Feature\\UserTest::it(.*)$/'

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Tests:  
Assertions:  0
Time:  0s
```

**Comment by eerison** [comment]
@olivernybroe you were right, the problem is this `App` (and test with lowercase)

it works

```
php /app/vendor/pestphp/pest/bin/pest --teamcity --configuration /app/phpunit.xml.dist /app/tests/Feature/UserTest.php --filter='/^P\\Tests\\Feature\\UserTest::it\sis\sa\stest\smyuniquetest.(\swith\s\(.*\)(\s#\d+)?)?$/'

Pest 1.20.0
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.11
Configuration: /app/phpunit.xml.dist
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Testing /app/tests/Feature/UserTest.php
  /app/tests/Feature/UserTest.php

##teamcity[testCount count='1' flowId='324']
##teamcity[testSuiteStarted name='/app/tests/Feature/UserTest.php' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='324']
  Tests\Feature\UserTest 

##teamcity[testSuiteStarted name='Tests\Feature\UserTest' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='324']
##teamcity[testStarted name='it is a test myuniquetest.' locationHint='pest_qn:///app/tests/Feature/UserTest.php::it is a test myuniquetest.' flowId='324']
##teamcity[testFinished name='it is a test myuniquetest.' duration='735' flowId='324']
✓ it is a test myuniquetest.


##teamcity[testSuiteFinished name='Tests\Feature\UserTest' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='324']


##teamcity[testSuiteFinished name='/app/tests/Feature/UserTest.php' locationHint='pest_qn:///app/tests/Feature/UserTest.php' flowId='324']
Tests:  1 passed
Assertions:  1
Time:  0.7352737s
```

any idea how to fix it?

**Comment by olivernybroe** [comment]
@eerison Awesome! Thanks a lot for doing all of this troubleshooting for me and for sharing the repo, thought it was closed source 😅 

So actually, I think I might know a fix, try to change the working directory in this run configuration window to be your `app` folder 🤔

**Comment by eerison** [comment]
> https://github.com/pestphp/pest-intellij/blob/main/src/main/kotlin/com/pestphp/pest/PestNamingUtil.kt#L61-L88

Thank you @olivernybroe I'll check how I can resolve it, I guess now I have a clear path to debug this problem.

**Comment by olivernybroe** [comment]
@eerison thanks for the interest in actually wanting to solve this yourself. ❤️ 

There are multiple ways to test it out, one is to use the `runIde` gradle command, which will spawn a new intelliJ instance while running the plugin.
Another way is to run the `buildPlugin`, which will give you a zip file you can install in phpstorm.

I do however not mind fixing this bug for you, if it works with the changes I suggested, then I think what has to be changed is basically instead of taking deciding the base directory based on the working directory, we do it based on where the composer.json file is located 🤔 
![image](https://user-images.githubusercontent.com/5870441/141790699-ca262326-b21e-4e88-9ef7-f253a538207e.png)

**Comment by olivernybroe** [comment]
I tried cloning your project and setting the Custom Working Directory and it fixed the issue for me :)

**Comment by eerison** [comment]
> I tried cloning your project and setting the Custom Working Directory and it fixed the issue for me :)

what do you mean `Setting the Custom Working Directory`

**Comment by eerison** [comment]
<img width="1071" alt="Screenshot 2021-11-16 at 17 46 36" src="https://user-images.githubusercontent.com/6358755/142028473-4c3ebd9a-d878-4405-92ea-1895d8f0802b.png">

Thank you @olivernybroe after I set the `Custom Work Directory` it works ❤️ 

I just need to create a template for every test get from this configuration.

**Comment by olivernybroe** [comment]
@eerison in the configuration window in the left corner you can change the default template that they are created from 👍 

I am also working on a solution for this, where it defines the path used based on the location of the composer file instead of the current working directory

**Comment by olivernybroe** [comment]
@eerison I have created an EAP which should solve the issue with the need for you to set the CWD 👍 

If you wanna test it out, here is the EAP.
[PEST PHP-1.2.2-EAP.3.zip](https://github.com/pestphp/pest-intellij/files/7555529/PEST.PHP-1.2.2-EAP.3.zip)

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
