### ISSUE TITLE
Changing & saving ENV variables in a not 

### ISSUE THREAD

**Issue by nicolasbinet** [pestphp/pest-intellij#212]
Hi,

When running tests through the plugin I'm getting a "mysql command" not found.

It's probably linked to the fact that MySQL has been installed through DBngin and is available in it's own path "/Users/Shared/DBngin/mysql/8.0.19/bin" not the "/usr/sbin:/usr/bin".

The path is set correctly in my default ZSH shell, but the Pest plugin is ran through .sh.

Is there any way to change that ?

I've also tried to change ENV variables in the plugin but they don't seem to stick.
Can it be set for the whole project in PhpStorm ?

Noted, that it works with no problem with vendor/bin/pest in PhpStorm terminal.

Nicolas

**Comment by olivernybroe** [comment]
Hmm that is quite weird, I am using a standard component from intellij for that. I think it's just an oversight from intellij, they have a lot of those unfortunately.

But nice to hear that you fixed it! 💯 

Do you have other issues here or can be close the issue? 😄

**Comment by nicolasbinet** [comment]
@olivernybroe thanks for the reply.

Can I ask what the component name is ?
I may make some more searching to understand the ins and outs

And yes for me, the ticket can be closed.

**Comment by olivernybroe** [comment]
As far as I remember, it is this one 🤔 
https://github.com/pestphp/pest-intellij/blob/main/src/main/kotlin/com/pestphp/pest/configuration/PestTestRunConfigurationEditor.kt
