### ISSUE TITLE
Support autocompletion on higher order expectations

### ISSUE THREAD

**Issue by lukeraymonddowning** [pestphp/pest-intellij#229]
As per our discussion the other day, here are the basic requirements for autocompletion on higher order expectations.

Currently, you do get autocompletion for the first property:

```php
// This works with full autocomplete
expect($object)
  ->foo->toBeString();  
```

However, once we move past the first expectation methods and on to a second (or third, fourth etc) property, we lose autocomplete.

```php
// I don't get autocomplete for anything past the very first property
expect($object)
  ->foo->toBeString()
  ->bar()->baz->toBeInt() // No autocomplete
  ->pest->is->best; // No autocomplete
```

The basic rule is that anything after `expect($value)` should return auto completions for both the expectation api methods AND the object passed in to `expect`. Taking it one step further, it is possible to do nested higher order expectations, `->foo->bar->toBeString()`, so in this case it should autocomplete based on the return type of `foo` as well as providing autocompletion for the expectation api methods in case we want to simple perform expectation methods on `foo` (in this case).

Here's a real life example from Larastreamers:

```php
expect($channel)
         ->youTubeCustomUrl->toBe('christophrumpel')
         ->name->toBe('Christoph Rumpel')
         ->description->toStartWith('Hi, I\'m Christoph Rumpel')
         ->onPlatformSince->toIso8601String()->toBe('2010-01-12T19:15:29+00:00')
         ->country->toBe('AT')
```

I hope that makes some form of sense 😄

Kind Regards,
Luke

**Comment by lukeraymonddowning** [comment]
Edge cases:

```
expect($object)
         ->something->toBe('firstObject')
         ->and($anotherObject)
         ->something->toBe('otherObject')
```

They could also chain another `expect` instead of `and`

**Comment by olivernybroe** [comment]
@adelf this is pretty similar to `HigherOrderCollectionProxy`, do you maybe have some great insights or ideas on how to solve this? 

I did try once to solve it for `HigherOrderCollectionProxy` in the collector plugin, but only solved 1/3 of the issue...
https://github.com/olivernybroe/collector-intellij/blob/main/src/main/kotlin/dev/nybroe/collector/types/HigherOrderTypeProvider.kt

**Comment by adelf** [comment]
It probably could be covered by completion contributor, inspection suppressor and type provider.
Do you have tests for that?

**Comment by olivernybroe** [comment]
@adelf Hmm interesting 🤔 

Yes, I have a branch with failing tests for this feature. Just created a PR #233 with it 👍

**Comment by olivernybroe** [comment]
This is now in the current EAP 💯
