### ISSUE TITLE
Add support for running pest on phpunit.xml file

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#23]
RIght now you can run tests by right clicking a folder or a file, however you still cannot do it by phpunit.xml file.

**Comment by olivernybroe** [comment]
@YusufGandhi Thanks for the kind words!

Hmm, just to follow, so by opening you mean showing the text inside the file in a separate window?  
This is indeed something that works for me and the plugin should not impact that.
![image](https://user-images.githubusercontent.com/5870441/131799698-c92d8f77-fffc-4255-8022-60c8450c1c35.png)

Steps I think you could try
- Try invalidating the cache
![image](https://user-images.githubusercontent.com/5870441/131799848-6f0792e5-4e3c-4499-921b-714b03402251.png)
- If that does not work, try disabling this plugin and see if the issue persist.

**Comment by YusufGandhi** [comment]
Ah, I think I didn't write my message clearly. Apology for that. So, here are a couple of animated gifs to explain it better.

I have finished running a test class using PEST. And tried to open a unit test (in this case a failed one). However, when I double-clicked the name of the unit test, it wouldn't open automatically on IDE's editor.

![2021-09-24_07-16-06 (1)](https://user-images.githubusercontent.com/2329909/134601503-b8d4a14b-59da-4f15-a2a5-dba4b8baed1c.gif)

As a comparison to using PHPUnit, when I double-clicked the name of a unit test, it would automatically open and focus on the unit test method as shown in the following gif.

![2021-09-24_07-30-26 (1)](https://user-images.githubusercontent.com/2329909/134601667-87aa57cd-d354-4ea0-8812-b8716d90bbd0.gif)

Is this behavior expected when we use PEST?

**Comment by olivernybroe** [comment]
@YusufGandhi What you are describing here is not related to this issue.

However this should work and does indeed work for me. 
Could you please verify that you are running the newest version of both the IntelliJ plugin and Pest itself?
If this is still and issue, try taking the command it runs and run it manually in the terminal and copy the output here, so I can see what is wrong with it 👍 

If so, please create this in a new issue and we can continue the troubleshoot there.
