### ISSUE TITLE
Unknow option "--no-ansi"

### ISSUE THREAD

**Issue by gakkiismywife** [pestphp/pest-intellij#238]
![image](https://user-images.githubusercontent.com/40749544/145766535-82638f07-bf36-420b-944a-f712c9b0a0c5.png)

**Comment by gakkiismywife** [comment]
![image](https://user-images.githubusercontent.com/40749544/145766584-4963c07f-9771-468f-8a03-818881fb7c9d.png)

**Comment by olivernybroe** [comment]
Looking at the second screenshot it seems like the window for setting up PHPSpec not Pest.

**Comment by gakkiismywife** [comment]
@olivernybroe Sorry ! My fault!

**Comment by olivernybroe** [comment]
@gakkiismywife haha, no worries! Good luck pesting!
