### ISSUE TITLE
Test file not found, when not run in root

### ISSUE THREAD

**Issue by TiiFuchs** [pestphp/pest-intellij#254]
I have a test project, that includes a package I'm working on in packages/my-library.

The Pest tests I want to execute are in that package. So there is a phpunit.xml in packages/my-library and the tests itself are located in packages/my-library/tests.

I installed the dependencies inside the packges/my-library folder (including pest) and configured the plugin in PhpStorm to point the Pest executable to the packages/my-library/vendor/bin/pest and the Default configuration file to packages/my-library/phpunit.xml.

When I try to run the tests from the command line (outside PhpStorm) `vendor/bin/pest` it works like expected.

When I try to run the tests from inside PhpStorm it fails. It doesn't matter if I try it on a single test function, a file or the whole folder. The error I get is: Test framework quit unexpectedly

```
/opt/homebrew/bin/php /.../packages/my-library/vendor/bin/pest --teamcity --configuration /.../packages/my-library/phpunit.xml /.../packages/my-library/tests/Unit/ReplyKeyboardTest.php "--filter=/^P\\Packages\\my-library\\tests\\Unit\\ReplyKeyboardTest::it\screates\svalid\sJSON(\swith\s((data\sset\s\".*\")|(\(.*\)(\s#\d+)?)))?$/"
Testing started at 20:26 ...

Pest 1.21.2

   Pest\Exceptions\ShouldNotHappen 

  
This should not happen - please create an new issue here: https://github.com/pestphp/pest.

- Issue: Test file not found.
- PHP version: 8.1.4
- Operating system: Darwin

  at packages/my-library/vendor/pestphp/pest/src/Exceptions/ShouldNotHappen.php:38
     34▕      * Creates a new instance of should not happen without a specific exception.
     35▕      */
     36▕     public static function fromMessage(string $message): ShouldNotHappen
     37▕     {
  ➜  38▕         return new ShouldNotHappen(new Exception($message));
     39▕     }
     40▕ }
     41▕

      +3 vendor frames 
  4   packages/my-library/tests/Unit/ReplyKeyboardTest.php:10
      it("it creates valid JSON", Object(Closure))

Process finished with exit code 1
```

When I change the Run Configuration for this test and specify the working directory explicitly to be packages/my-library, the framework quits unexpectedly too, but I get no error from Pest. The output is as follows:

```
/opt/homebrew/bin/php /.../packages/my-library/vendor/bin/pest --teamcity --configuration /.../packages/my-library/phpunit.xml /.../packages/my-library/tests/Unit/ReplyKeyboardTest.php "--filter=/^P\\Packages\\my-library\\tests\\Unit\\ReplyKeyboardTest::it\screates\svalid\sJSON(\swith\s((data\sset\s\".*\")|(\(.*\)(\s#\d+)?)))?$/"
Testing started at 20:30 ...

Pest 1.21.2
PHPUnit 9.5.19 #StandWithUkraine

Tests:  
Assertions:  0
Time:  0s

Process finished with exit code 0
```

For readability and privacy I shortened the paths to the project root.

I'm not sure how I can fix this. Any ideas?

**Comment by TiiFuchs** [comment]
So apparently I need to specify the working directory to fix the big error. (But I'd assume, that the working directory should always be the folder containing the phpunit.xml, right?)

Additionally the second problem is, that the IntelliJ Plugin does not correctly set the --filter argument right. So no test is found (because it does not match), and nothing is run.

**Comment by olivernybroe** [comment]
@TiiFuchs So the big error you were getting seems like pest itself should handle it to give a better error message 🤔 


So the other issue with the filter being generated from root is actually not entirely correct, it is actually generated from the the parent folder of the vendor folder. 
https://github.com/pestphp/pest-intellij/blob/8520a87f23a86060a1322d747d882ad204ac4498/src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationHandler.kt#L75-L77

This is actually done this way to reflect how pest itself works, however we might have messed it up 😅 



Could you try something for me and run `vendor/bin/pest --list-tests`, so we can see what the actual names of your tests are, so we are sure we generate the filters correctly.

Also does your project contain multiple composer folders? You said you had a `packages/my-library/vendor`, but do you also have a `project/vendor` folder? 
Phpstorm does not currently support multiple composer projects inside one project.
https://youtrack.jetbrains.com/issue/WI-31260

**Comment by TiiFuchs** [comment]
Yeah of course. Currently the tests are named like this:

```
PHPUnit 9.5.19 #StandWithUkraine

Available test(s):
 - P\Tests\Unit\ForceReplyTest::it creates valid JSON
 - P\Tests\Unit\ForceReplyTest::it can set known fields
 - P\Tests\Unit\ForceReplyTest::it can set unknown fields
 - P\Tests\Unit\InlineKeyboardButtonTest::it creates valid JSON
 - P\Tests\Unit\InlineKeyboardButtonTest::it can set known fields
 - P\Tests\Unit\InlineKeyboardButtonTest::it can set text via make
 - P\Tests\Unit\InlineKeyboardButtonTest::it can set unknown fields
 - P\Tests\Unit\InlineKeyboardTest::it creates valid JSON
 - P\Tests\Unit\InlineKeyboardTest::it can set unknown fields
 - P\Tests\Unit\InlineKeyboardTest::it can has multiple buttons
 - P\Tests\Unit\InlineKeyboardTest::it can has multiple rows
 - P\Tests\Unit\KeyboardButtonPollTypeTest::it creates any type
 - P\Tests\Unit\KeyboardButtonPollTypeTest::it creates quiz type
 - P\Tests\Unit\KeyboardButtonPollTypeTest::it creates regular type
 - P\Tests\Unit\KeyboardButtonPollTypeTest::it creates unknown type
 - P\Tests\Unit\KeyboardButtonTest::it creates valid JSON
 - P\Tests\Unit\KeyboardButtonTest::it can set known fields
 - P\Tests\Unit\KeyboardButtonTest::it can set text via make
 - P\Tests\Unit\KeyboardButtonTest::it can set unknown fields
 - P\Tests\Unit\ReplyKeyboardRemoveTest::it creates valid JSON
 - P\Tests\Unit\ReplyKeyboardRemoveTest::it can set known fields
 - P\Tests\Unit\ReplyKeyboardRemoveTest::it can set unknown fields
 - P\Tests\Unit\ReplyKeyboardTest::it creates valid JSON
 - P\Tests\Unit\ReplyKeyboardTest::it can set known fields
 - P\Tests\Unit\ReplyKeyboardTest::it can set unknown fields
 - P\Tests\Unit\ReplyKeyboardTest::it can has multiple buttons
 - P\Tests\Unit\ReplyKeyboardTest::it can has multiple rows
```

It belongs to this repository: https://github.com/php-telegram-bot/fluent-keyboard

**Comment by TiiFuchs** [comment]
For a clearer picture. The folder structure of the project looks like this:

```
.
├── app
├── bootstrap.php
├── composer.json
├── composer.lock
├── docker-compose.yml
├── handle.php
├── helpers.php
├── logs
├── packages
│  └── fluent-keyboard
│     ├── composer.json
│     ├── composer.lock
│     ├── phpunit.xml
│     ├── src
│     │  ├── FluentEntity.php
│     │  ├── ForceReply.php
│     │  ├── helpers.php
│     │  ├── InlineKeyboard
│     │  │  ├── InlineKeyboardButton.php
│     │  │  └── InlineKeyboardMarkup.php
│     │  ├── ReplyKeyboard
│     │  │  ├── KeyboardButton.php
│     │  │  ├── KeyboardButtonPollType.php
│     │  │  └── ReplyKeyboardMarkup.php
│     │  └── ReplyKeyboardRemove.php
│     └── tests
│        ├── Pest.php
│        └── Unit
│           ├── ForceReplyTest.php
│           ├── InlineKeyboardButtonTest.php
│           ├── InlineKeyboardTest.php
│           ├── KeyboardButtonPollTypeTest.php
│           ├── KeyboardButtonTest.php
│           ├── ReplyKeyboardRemoveTest.php
│           └── ReplyKeyboardTest.php
└── README.md
└── vendor
```

So there is a root composer.json/vendor folder. But the test part is happening inside packages/fluent-keyboard.

I guess the `ComposerLibraryManager.getInstance(project).findVendorDirForUpsource()` points to the root vendor folder.

**Comment by olivernybroe** [comment]
Yeah, so the issue you are having is that you are actually trying to use one phpstorm project for multiple projects.  
Unfortunately this is simply just unsupported by the structure of phpstorm. It does not support having multiple projects inside one project.

The official statement from phpstorm would be that you should simply have a phpstorm project for `fluent-keyboard`. So I have mainly gone with that restriction. 


However I do not mind changing this so it works for your project, as I hate this restriction from phpstorm 😆 
So just to loop you in, the reason why we do it from the composer path is actually because of this #211.

I am thinking we could change the logic so if the cwd is not the same as the project root path, then we use that as the root path for the filter method, else we use the composer path 🤔 
However before building this, I will quickly create a version which uses cwd instead of composer, just to check if it even solves your issues 👍 

I have created a new build for you with this change, could you check if it works for you?


Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.3.1-EAP.4.zip](https://github.com/pestphp/pest-intellij/files/8340965/PEST.PHP-1.3.1-EAP.4.zip)

**Comment by TiiFuchs** [comment]
I will try the new build in a few seconds...

In the mean time I tried to run the tests from the project root (configuring phpunit.xml in root project to point to `./packages/fluent-keyboard/tests` and installing pest there too.)

This works, for run configuration and run file. But the filter is not correctly generated if you just run a specific test.

`vendor/bin/pest --list-tests` now results in (shortened):
```
 - P\Packages\fluentkeyboard\tests\Unit\ForceReplyTest::it creates valid JSON
 - P\Packages\fluentkeyboard\tests\Unit\ForceReplyTest::it can set known fields
 - P\Packages\fluentkeyboard\tests\Unit\ForceReplyTest::it can set unknown fields
```

Actually this was executed:
```
/opt/homebrew/bin/php /Users/tii/projects/telegram/php-telegram-bot/vendor/bin/pest --teamcity --configuration /Users/tii/projects/telegram/php-telegram-bot/phpunit.xml /Users/tii/projects/telegram/php-telegram-bot/packages/fluent-keyboard/tests/Unit/ReplyKeyboardTest.php "--filter=/^P\\Packages\\fluent-keyboard\\tests\\Unit\\ReplyKeyboardTest::it\scan\shave\smultiple\srows(\swith\s((data\sset\s\".*\")|(\(.*\)(\s#\d+)?)))?$/"
```

So it seems Pest generates fluentkeyboard without the `-`, but the filter keeps the `-`.
But if I run the complete line from the command line and remove the `-`, it still does not work. But my understanding of the filter parameter ends there. I don't get the end of the filter stuff... :D 

-----

I will try the custom build running from the package folder now...

**Comment by TiiFuchs** [comment]
So regarding the new build:

Running the phpunit.xml: works if the working directory is set to the package folder. If not the following error appears:
```
   Pest\Exceptions\TestAlreadyExist 

  A test with the description `it creates valid JSON` already exist in the filename `/Users/tii/projects/telegram/php-telegram-bot/packages/fluent-keyboard/vendor/bin/pest`.
```

Running a folder: Same as configuration above.

Running a specific file: Works without explicitly setting the working directory

Running a single test: Same problem with --filter parameter as earlier.

So progress... But not quite there, I guess. 🤔

**Comment by olivernybroe** [comment]
@TiiFuchs ah thanks for testing it out. 

So from this it seems we had two issues for you, the next is related to to us not filtering `-` aways, as pest apparently does this. 🤔 

Haha yeah, the regex generated for the filter is quite complex, the complexity in the end is for making it work with datasets.


I have created a new build for you which filters away `-`. This at least seem to work for me when testing out locally.

Could you test out this new build and see if it then works for you? 👍 

[PEST PHP-1.3.1-EAP.5.zip](https://github.com/pestphp/pest-intellij/files/8348737/PEST.PHP-1.3.1-EAP.5.zip)

**Comment by TiiFuchs** [comment]
Yup, the `-` is gone, and when I specify a Custom Working Dir on each Run Configuration the test functions get executed on its own.

Without the custom working dir the filter is still generated from the root folder (containing Packages/fluentkeyboard). 

`--filter=/^P\\Packages\\fluentkeyboard\\tests\\Unit\\ForceReplyTest::it\scan\sset\sknown\sfields(\swith\s((data\sset\s\".*\")|(\(.*\)(\s#\d+)?)))?$/`

So it's at least able to function properly now. But it's a bit of an overwhelming work if you always have to change the working dir before running it, if you've never run that specific run configuration/test function before. It's not a quick click on the run button besides the function as it is supposed to be (imho).

What are your thought on that?

**Comment by olivernybroe** [comment]
@TiiFuchs You can change the template so you don't have to do it for every single run configuration 👍 
https://github.com/pestphp/pest-intellij/issues/211#issuecomment-970554652


Hmm, I agree. We need to figure out a better path for deciding what the root directory should be, as I also want it to be as simple as just press run 🤔 
Just unsure what could be the right way to figure out the root. Maybe we can do it from the path of the pest binary instead?

**Comment by TiiFuchs** [comment]
Shouldn't it be the folder in which the phpunit.xml resides? 🤔

Since the phpunit.xml has relative paths to the tests and how to identify them...
And you can specify the phpunit.xml to use in the Plugin configuration.

At least that sounds logical to me.

**Comment by TiiFuchs** [comment]
plus you could theoretically use a globally installed pest binary and it still would work. (at least in this scenario.)

**Comment by olivernybroe** [comment]
I don't think pest supports being globally installed 🤔 

Hmm, but maybe you are right that we can do it from the path of the phpunit.xml instead. Trying to think of edge-case scenarios, but don't think I have a deep enough knowledge of phpunit.xml to know what you are allowed to do with it 🤔

**Comment by TiiFuchs** [comment]
Sadly my knowledge is limited to here ^^

**Comment by olivernybroe** [comment]
I'll try and make a build which uses the `phpunit.xml` file to determine root path and then we can test that out 👍

**Comment by olivernybroe** [comment]
[PEST PHP-1.3.1-EAP.7.zip](https://github.com/pestphp/pest-intellij/files/8349292/PEST.PHP-1.3.1-EAP.7.zip)
@TiiFuchs Could you please try out if this version is still working for you?

**Comment by TiiFuchs** [comment]
Uhhm... I think it behaves like before:

Without specifying a working directory it does not execute the test, although the filter seems to be right this time:
`"--filter=/^P\\Tests\\Unit\\KeyboardButtonPollTypeTest::it\screates\sregular\stype(\swith\s((data\sset\s\".*\")|(\(.*\)(\s#\d+)?)))?$/"`
`P\Tests\Unit\KeyboardButtonPollTypeTest::it creates regular type`

Does it get executed from the phpunit.xml path too or did the change only affect the filter generation?

With specifying the working dir, it works. Like it did before.

**Comment by olivernybroe** [comment]
Haha oops, my bad... 

Alright, so lets try again again again... 😅 

I have now done so if you have a custom working directory defined that is used, else the the parent dir of phpunit.xml is used
[PEST PHP-1.3.1-EAP.8.zip](https://github.com/pestphp/pest-intellij/files/8349694/PEST.PHP-1.3.1-EAP.8.zip)

**Comment by TiiFuchs** [comment]
Nice! This build works like I'd expect it!!! 🎉

Without explicitly configuring the working dir, configuration/dir/file/function tests all work like a charm!!!

**Comment by olivernybroe** [comment]
Yaaay! 🎉 

Alright, I'll try and clean it up a bit and then hopefully in the next week or two have time to tag v1.4.0 💯 


Thanks for your help, it's really nice when people are willing to help out solving the issue

**Comment by olivernybroe** [comment]
This has now been released as the next stable version.
https://github.com/pestphp/pest-intellij/releases/tag/v1.4.0

There might go a couple of days before it's available in marketplace.
