### ISSUE TITLE
Icons doesn't work well on dark theme

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#27]
Right now we have some awesome custom icons, however they do not look that good when used with a dark theme.

We should either fix the icons to work great on both or have two set of icons, one for light and one for dark theme.

Dark theme:
![image](https://user-images.githubusercontent.com/5870441/87634042-d0025380-c73c-11ea-8c1f-a8a0e00bd9dc.png)
Light theme:
![image](https://user-images.githubusercontent.com/5870441/87957070-1a266480-cab0-11ea-92ea-9ba552d39aeb.png)

Phpunit icons:
![image](https://user-images.githubusercontent.com/5870441/87957410-830ddc80-cab0-11ea-8142-dc15aef02aef.png)

**Comment by olivernybroe** [comment]
@caneco 🙏

**Comment by olivernybroe** [comment]
A consideration is also doing the exact same as phpunit and use the basic arrows, and not having the pest icon with it.

I kinda like the speciality of having pest icons there, not sure what you guys think though 😄

**Comment by caneco** [comment]
@olivernybroe it's there a way to load a different set?

**Comment by olivernybroe** [comment]
@caneco I can check if we are in dark mode or not. 

So we can load different icons based on light or dark mode.

**Comment by caneco** [comment]
@olivernybroe in that case I will get you a different set for Dark Mode 🌔

**Comment by caneco** [comment]
@olivernybroe, first of all… sorry about the (very) late response.

Here's a suggestion for the two sets of icons: **light** and **dark**.

![image](https://user-images.githubusercontent.com/502041/89694538-df725800-d908-11ea-88d7-fb7fec149e50.png)

**Comment by olivernybroe** [comment]
@caneco No worries, we have no rush 👍 

Could you try showing it with `#323232` as the background color? That is the default dark mode color in Intellij 😄

**Comment by caneco** [comment]
Here you have it 😁 
That actually made me switch some colours.

![image](https://user-images.githubusercontent.com/502041/89872247-96dcc800-dbb0-11ea-9d51-81028c3f711a.png)

What do you think? It will work?

**Comment by olivernybroe** [comment]
Yeah, that's amazing! 👍 Let's use that for dark mode icons

**Comment by olivernybroe** [comment]
We now got dark icons, now I just have to update the plugins to use them and we can close this issue!
