### ISSUE TITLE
Pest icon : False positive 

### ISSUE THREAD

**Issue by bastien-phi** [pestphp/pest-intellij#28]
It looks like there can be false positive for the icon on test files.

This occured in phpstan-src tests directory with version 0.2.1-alpha.2.

![image](https://user-images.githubusercontent.com/10199039/87758551-f1327500-c80c-11ea-87c4-57d6bf56c43c.png)

**Comment by olivernybroe** [comment]
Thanks for reporting this. 

Looks like it is recognising the method call to `test` as a pest test call.

**Comment by olivernybroe** [comment]
A release will be made shortly with a fix for this. It might take 1-2 days before it it approved by jetbrains.
