### ISSUE TITLE
Collision output for exceptions

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#29]
Right now exceptions are shown with the default phpunit output, however as pest requires collision, I think it makes sense to use collision output for exceptions when showing it in phpstorm.

For doing this I think we need to create a new phpunit printer, which outputs in the teamcity format that phpstorm understand, but uses collision output. 

Thanks @roni-estein for the suggestion.

**Comment by roni-estein** [comment]
So excited for this!
  

  
  

  
  
>

**Comment by olivernybroe** [comment]
Alright, so I did a small investigation regarding this feature. 

This should be solved in PHP code, not in the plug-in.

For solving this a new phpunit test printer has to be added. This printer has to follow the teamcity format, but use descriptions from collision. 

We can have this printer located multiple different places

- in this plug-in
- in pest
- in collision

By storing it in collision, the advantage would be that collision results could also be used for phpunit in phpstorm.

By storing it in pest, the advantage would be that we could easily do a bunch of custom formattering, if that would ever be needed.

By storing it in this plug-in, the advantage would be that we are not depending on the feature being available in the other tools. 


I am leaning mostly to storing it in pest, as I think that would be easiest.
@nunomaduro what do you think?

**Comment by olivernybroe** [comment]
I'll close this issue as the phpstorm plugin has done all of the work it can do on it. 

For this to work, the printer in pest has to use collision as the output for exceptions.
An issue has been opened in pest about this.

https://github.com/pestphp/pest/issues/188
