### ISSUE TITLE
Error sending phpstorm report

### ISSUE THREAD

**Issue by CrazyBoy49z** [pestphp/pest-intellij#303]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3448603/168387160-c752e332-f5e2-4f2c-9e4f-f37708d832bf.png">

https://github.com/pestphp/pest-intellij/issues/new?body=%7C+Q++++++++++++++++%7C+A%0A%7C+----------------+%7C+-----%0A%7C+Bug+report%3F++++++%7C+yes%0A%7C+Plugin+version+++%7C+1.4.2%0A%7C+Pest+version+++++%7C+x.y.z%0A%7C+IntelliJ+version+%7C+PS-221.5591.58%0A%7C+OS+++++++++++++++%7C+Mac+OS+X%0A%0A%23%23%23+Description%0A%3CFILL+OUT+THE+DESCRIPTION%3E%0A%0A%23%23%23+Stacktrace%0A%60java.lang.ClassCastException%3A+class+com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl%24%24Lambda%245955%2F0x0000000802ad4840+cannot+be+cast+to+class+%5BLjava.lang.Object%3B+%28com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl%24%24Lambda%245955%2F0x0000000802ad4840+is+in+unnamed+module+of+loader+com.intellij.ide.plugins.cl.PluginClassLoader+%406a0195af%3B+%5BLjava.lang.Object%3B+is+in+module+java.base+of+loader+%27bootstrap%27%29%60%0A%0A%60%60%60%0Ajava.lang.ClassCastException%3A+class+com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl%24%24Lambda%245955%2F0x0000000802ad4840+cannot+be+cast+to+class+%5BLjava.lang.Object%3B+%28com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl%24%24Lambda%245955%2F0x0000000802ad4840+is+in+unnamed+module+of+loader+com.intellij.ide.plugins.cl.PluginClassLoader+%406a0195af%3B+%5BLjava.lang.Object%3B+is+in+module+java.base+of+loader+%27bootstrap%27%29%0A%09at+com.intellij.util.SmartList.asArray%28SmartList.java%3A160%29%0A%09at+com.intellij.util.SmartList.resizeIfNecessary%28SmartList.java%3A92%29%0A%09at+com.intellij.util.SmartList.add%28SmartList.java%3A81%29%0A%09at+com.intellij.util.containers.ContainerUtil.add%28ContainerUtil.java%3A1954%29%0A%09at+com.jetbrains.php.config.interpreters.PhpInterpretersBaseManager.addListener%28PhpInterpretersBaseManager.java%3A48%29%0A%09at+com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.addListener%28PhpInterpretersManagerImpl.java%3A305%29%0A%09at+com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.registerInterpreterStateListeners%28PhpInterpretersManagerImpl.java%3A125%29%0A%09at+com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.%3Cinit%3E%28PhpInterpretersManagerImpl.java%3A59%29%0A%09at+java.base%2Fjdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0%28Native+Method%29%0A%09at+java.base%2Fjdk.internal.reflect.NativeConstructorAccessorImpl.newInstance%28NativeConstructorAccessorImpl.java%3A62%29%0A%09at+java.base%2Fjdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance%28DelegatingConstructorAccessorImpl.java%3A45%29%0A%09at+java.base%2Fjava.lang.reflect.Constructor.newInstance%28Constructor.java%3A490%29%0A%09at+com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer%28constructorInjection.kt%3A52%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection%28ComponentManagerImpl.kt%3A891%29%0A%09at+com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize%28ServiceComponentAdapter.kt%3A51%29%0A%09at+com.intellij.serviceContainer.ServiceComponentAdapter.access%24createAndInitialize%28ServiceComponentAdapter.kt%3A12%29%0A%09at+com.intellij.serviceContainer.ServiceComponentAdapter%24doCreateInstance%241.compute%28ServiceComponentAdapter.kt%3A45%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun%28CoreProgressManager.java%3A683%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress%28CoreProgressManager.java%3A639%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection%28CoreProgressManager.java%3A238%29%0A%09at+com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance%28ServiceComponentAdapter.kt%3A44%29%0A%09at+com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached%28BaseComponentAdapter.kt%3A119%29%0A%09at+com.intellij.serviceContainer.BaseComponentAdapter.getInstance%28BaseComponentAdapter.kt%3A73%29%0A%09at+com.intellij.serviceContainer.BaseComponentAdapter.getInstance%24default%28BaseComponentAdapter.kt%3A66%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.doGetService%28ComponentManagerImpl.kt%3A610%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.getService%28ComponentManagerImpl.kt%3A584%29%0A%09at+com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession%28ClientAwareComponentManager.kt%3A37%29%0A%09at+com.intellij.openapi.client.ClientAwareComponentManager.getService%28ClientAwareComponentManager.kt%3A22%29%0A%09at+com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.getInstance%28PhpInterpretersManagerImpl.java%3A51%29%0A%09at+com.jetbrains.php.config.PhpProjectConfigurationFacade.getInterpreter%28PhpProjectConfigurationFacade.java%3A80%29%0A%09at+com.jetbrains.php.testFramework.run.PhpTestRunConfiguration.getInterpreter%28PhpTestRunConfiguration.java%3A393%29%0A%09at+com.jetbrains.php.testFramework.run.PhpTestRunConfiguration.%3Cinit%3E%28PhpTestRunConfiguration.java%3A87%29%0A%09at+com.pestphp.pest.configuration.PhpTestRunConfiguration.%3Cinit%3E%28PhpTestRunConfiguration.java%3A16%29%0A%09at+com.pestphp.pest.configuration.PestRunConfiguration.%3Cinit%3E%28PestRunConfiguration.kt%3A33%29%0A%09at+com.pestphp.pest.configuration.PestRunConfigurationType.createTemplateConfiguration%28PestRunConfigurationType.kt%3A21%29%0A%09at+com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration%28ConfigurationFactory.java%3A64%29%0A%09at+com.intellij.execution.impl.RunManagerImpl.createTemplateSettings%24intellij_platform_execution_impl%28RunManagerImpl.kt%3A353%29%0A%09at+com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate%28RunManagerImpl.kt%3A345%29%0A%09at+com.intellij.execution.impl.RunManagerImpl.createConfiguration%28RunManagerImpl.kt%3A270%29%0A%09at+com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfigurationStatic%28RunConfigurationProducer.java%3A257%29%0A%09at+com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfiguration%28RunConfigurationProducer.java%3A247%29%0A%09at+com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext%28RunConfigurationProducer.java%3A96%29%0A%09at+com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext%28RunConfigurationProducer.java%3A197%29%0A%09at+com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext%28PreferredProducerFind.java%3A118%29%0A%09at+com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext%28PreferredProducerFind.java%3A100%29%0A%09at+com.intellij.execution.actions.ConfigurationContext.getConfigurationsFromContext%28ConfigurationContext.java%3A412%29%0A%09at+com.intellij.execution.actions.ConfigurationContext.findPreferredConfiguration%28ConfigurationContext.java%3A291%29%0A%09at+com.intellij.execution.actions.ConfigurationContext.findExisting%28ConfigurationContext.java%3A284%29%0A%09at+com.intellij.execution.actions.BaseRunConfigurationAction.findExisting%28BaseRunConfigurationAction.java%3A60%29%0A%09at+com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate%28BaseRunConfigurationAction.java%3A215%29%0A%09at+com.intellij.execution.actions.BaseRunConfigurationAction.update%28BaseRunConfigurationAction.java%3A180%29%0A%09at+com.intellij.openapi.actionSystem.ex.ActionUtil.lambda%24performDumbAwareUpdate%240%28ActionUtil.java%3A131%29%0A%09at+com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate%28ActionUtil.java%3A145%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate%28ActionUpdater.java%3A645%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24updateActionReal%244%28ActionUpdater.java%3A126%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction%28ActionUpdater.java%3A176%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal%28ActionUpdater.java%3A127%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24new%240%28ActionUpdater.java%3A112%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.update%28ActionUpdater.java%3A634%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild%28ActionUpdater.java%3A478%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24doExpandActionGroup%2420%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.util.containers.ContainerUtil.concat%28ContainerUtil.java%3A1400%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild%28ActionUpdater.java%3A535%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24doExpandActionGroup%2420%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.util.containers.ContainerUtil.concat%28ContainerUtil.java%3A1400%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild%28ActionUpdater.java%3A535%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24doExpandActionGroup%2420%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.util.containers.ContainerUtil.concat%28ContainerUtil.java%3A1400%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild%28ActionUpdater.java%3A535%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24doExpandActionGroup%2420%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.util.containers.ContainerUtil.concat%28ContainerUtil.java%3A1400%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild%28ActionUpdater.java%3A535%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24doExpandActionGroup%2420%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.util.containers.ContainerUtil.concat%28ContainerUtil.java%3A1400%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild%28ActionUpdater.java%3A535%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24doExpandActionGroup%2420%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.util.containers.ContainerUtil.concat%28ContainerUtil.java%3A1400%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup%28ActionUpdater.java%3A457%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup%28ActionUpdater.java%3A260%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24expandActionGroupAsync%2412%28ActionUpdater.java%3A321%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24expandActionGroupAsync%2413%28ActionUpdater.java%3A339%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction%28ApplicationImpl.java%3A1152%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24tryRunReadActionAndCancelBeforeWrite%2417%28ActionUpdater.java%3A371%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite%28ProgressIndicatorUtils.java%3A158%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite%28ActionUpdater.java%3A367%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24expandActionGroupAsync%2414%28ActionUpdater.java%3A339%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.lambda%24runProcess%242%28CoreProgressManager.java%3A189%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.lambda%24executeProcessUnderProgress%2412%28CoreProgressManager.java%3A608%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun%28CoreProgressManager.java%3A683%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress%28CoreProgressManager.java%3A639%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress%28CoreProgressManager.java%3A607%29%0A%09at+com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress%28ProgressManagerImpl.java%3A60%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.runProcess%28CoreProgressManager.java%3A176%29%0A%09at+com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator%28BackgroundTaskUtil.java%3A365%29%0A%09at+com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda%24expandActionGroupAsync%2415%28ActionUpdater.java%3A338%29%0A%09at+com.intellij.util.concurrency.BoundedTaskExecutor.doRun%28BoundedTaskExecutor.java%3A241%29%0A%09at+com.intellij.util.concurrency.BoundedTaskExecutor.access%24200%28BoundedTaskExecutor.java%3A31%29%0A%09at+com.intellij.util.concurrency.BoundedTaskExecutor%241.execute%28BoundedTaskExecutor.java%3A214%29%0A%09at+com.intellij.util.ConcurrencyUtil.runUnderThreadName%28ConcurrencyUtil.java%3A212%29%0A%09at+com.intellij.util.concurrency.BoundedTaskExecutor%241.run%28BoundedTaskExecutor.java%3A203%29%0A%09at+java.base%2Fjava.util.concurrent.ThreadPoolExecutor.runWorker%28ThreadPoolExecutor.java%3A1128%29%0A%09at+java.base%2Fjava.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A628%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24PrivilegedThreadFactory%241%241.run%28Executors.java%3A668%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24PrivilegedThreadFactory%241%241.run%28Executors.java%3A665%29%0A%09at+java.base%2Fjava.security.AccessController.doPrivileged%28Native+Method%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24PrivilegedThreadFactory%241.run%28Executors.java%3A665%29%0A%09at+java.base%2Fjava.lang.Thread.run%28Thread.java%3A829%29%0A%0A%60%60%60

**Comment by olivernybroe** [comment]
hmm yeah, need to figure out another way to send exceptions with their stacktrace to github then a get request 👀

**Comment by olivernybroe** [comment]
The error reporter has been rebuild in the next EAP.
