### ISSUE TITLE
Refactor dataset name

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#320]
Allow for refactoring a dataset name will refactor all it's usages also.

**Comment by adelf** [comment]
BTW, is there any "Find usages" feature for datasets in the current release?

**Comment by olivernybroe** [comment]
Nope, that has not been created also. I have only implemented the reference provider 🤔

**Comment by adelf** [comment]
Let me try to implement these 2 features: find usages and probably renaming...

**Comment by olivernybroe** [comment]
Awesome! Thanks @adelf 😍
