### ISSUE TITLE
Pest with Coverage

### ISSUE THREAD

**Issue by zembrowski** [pestphp/pest-intellij#33]
Hey there, first off: awesome work with the plugin. Works incredible well for me.

Is it possible to run Pest in PhpStorm with Coverage, so the test coverage is already shown in the editor and project tree? (Works with PhpUnit without extra config.)

Currently not runnable (inactive, grayed out) in the "Run" menu in 2020.1.4 with v0.2.1-alpha.3

My workaround is to run it with an extra configuration and then open the results in a browser.

**Comment by olivernybroe** [comment]
Thanks for the feedback 👍 

Currently this is not possible and to be honest something I forgot completely about 😄

We can add support for coverage inside phpstorm so it works like any other code coverage engine.


Some scribbles here for implementation ideas (mostly for myself):
For adding coverage 3 extension points should be needed.

- programRunner
- coverageEngine
- coverageRunner

And a `coverageAnnotator` might also be needed.

As it is possible to have the plugin installed without having the coverage plugin enabled, it should be added as a new optional dependency, e.g.
```
<depends optional="true" config-file="pest-coverage.xml">com.intellij.modules.coverage</depends>
```

It might be possible to reuse most of the logic from phpunit implementation.

**Comment by olivernybroe** [comment]
Just opened a PR for the coverage support, would be awesome if anyone could test it out 👍 

I attached the file for installation from disk.
[pest-intellij-0.2.1-alpha.5.zip](https://github.com/pestphp/pest-intellij/files/5006093/pest-intellij-0.2.1-alpha.5.zip)

**Comment by zembrowski** [comment]
alpha.5 works just awesome out of the box. Tested with Xdebug and PCOV (which speeds the execution time a lot).

Does the plugin add some extra Xdebug related arguments to the executed command (cf. screenshot)? (It does not affect neither the usage of PCOV nor the execution time.)

<img width="1091" alt="Bildschirmfoto 2020-07-31 um 15 50 14" src="https://user-images.githubusercontent.com/2451083/89041817-4bbbed00-d346-11ea-9772-618dc06b3455.png">

**Comment by olivernybroe** [comment]
Awesome! Thanks for testing it out 👍 

Those arguments are added by phpstorm when I till it to enable debugger and it finds xdebug as your installed debugger.
Not sure what they all do exactly, but I think it's for sending data between xdebug and phpstorm 😄 

I'll try and finish up the pr, missing one feature as can be seen in the PR.
