### ISSUE TITLE
Navigate using "Go to Test" doesn't find pest tests

### ISSUE THREAD

**Issue by BertvanHoekelen** [pestphp/pest-intellij#34]
Normally when pressing cmd+shift+t in a class you can quickly navigate to the test with the same name. Or when you are in the test file you can quickly go to the class. 

## Class
src/Foo.php:
```php
<?php

class Foo
{
}
```

## PHPUnit test
tests/FooTest.php
```php
<?php

use PHPUnit\Framework\TestCase;

class FooTest extends TestCase
{

}
```
![Screenshot 2020-07-23 at 13 40 18](https://user-images.githubusercontent.com/7521173/88282544-0f571400-ccea-11ea-899a-09e459fadbd5.png)

## Pest test

tests/FooTest.php
```php
<?php

it('foo', function () {
    
});
```
![Screenshot 2020-07-23 at 13 41 28](https://user-images.githubusercontent.com/7521173/88282652-4299a300-ccea-11ea-86eb-3baff6d9ce94.png)

**Comment by olivernybroe** [comment]
Hmm, yeah so this would be a new feature.

Just to understand, how exactly do you want it to work? Like matching a pest test to a class?
The only way I can see it, is by doing it from the file name. 👍

**Comment by BertvanHoekelen** [comment]
Yeah it will be a new feature 🙂 (you guys are rocking it). Was migrating a package and came across this, so no worries.

Yeah I guess the PHPUnit implementation works by searching a class name with class name suffixed by test, or the other way around. I think doing the same but with filenames would be the way to go.

**Comment by olivernybroe** [comment]
@BertvanHoekelen Awesome, just wanted to make sure we had the same though on how it should work 😄 

Btw. if you haven't already, then check out (drift)[https://github.com/pestphp/drift], it's a project for migrating phpunit to pest tests.

**Comment by BertvanHoekelen** [comment]
Great! If you are able to give me some pointers I can try to solve it.

@olivernybroe Yes I have seen it :). Currently doing a manual migration to check if my team can fully switch to pest. It's those small productivity things that were blocking it, with the plugin we are almost there.

**Comment by olivernybroe** [comment]
Alright, so to implement this you have to implement this interface
https://github.com/JetBrains/intellij-community/blob/36f6e9d591452411382a63186820b107a5751170/platform/lang-api/src/com/intellij/testIntegration/TestFinder.java

And register that class in https://github.com/pestphp/pest-intellij/blob/master/src/main/resources/META-INF/plugin.xml as a new extension point.

To test it out, use the gradle task `runIDE`

**Comment by olivernybroe** [comment]
You can also implement the [`TestCreator](https://github.com/JetBrains/intellij-community/blob/36f6e9d591452411382a63186820b107a5751170/platform/lang-api/src/com/intellij/testIntegration/TestCreator.java) interface for adding support for creating tests with the goto command if no tests exist.

**Comment by olivernybroe** [comment]
So I looked into this a little today and seems like this is a bit more complicated. 

The reason is that finding the test for to navigate to is a bit more tricky. 
We need to create a new indexer which indexes all the pest test files, so we can search for the test file corresponding to a class in that index. 

This is also needed for navigating the other way, as the class `TestFinderHelper` is not called on the pest tests while the php indexers are running, as phpstorm did not think that tests would ever be outside of a php class. 

So the new indexer has to index all pest tests and call the `TestFinderHelper` on the pest test files.


Btw. mostly writing this for myself, but if anyone wanna try and tackle this, feel free :)

**Comment by olivernybroe** [comment]
I am creating a new issue for creating tests via the navigation window #54

**Comment by olivernybroe** [comment]
This will be part of `v0.4.0` when that is released. 

I'll make an EAP release tagged `v0.4.0-alpha.2` with it. `alpha.2` has some serious performance increases with the indexing compared to `alpha.1`
