### ISSUE TITLE
Make test result nicer

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#364]
Currently our test result output is not that clean, we should try and see what we can do to make it prettier.

Some suggestions we can try out in the plugin are:

- [ ] Scroll to bottom of output
- [ ] Hide command that we ran
- [x] Hide test started timestamp
- [ ] Hide process finished text

Any other suggestions which the plugin controls @christophrumpel?

**Comment by owenvoke** [comment]
Regarding "Hide command that we ran", is there any way we can have this as a toggle / config? Or have a button to pop up the command that was run? Sometimes it's quite useful to be able to copy the command. 🤷🏻

**Comment by olivernybroe** [comment]
@owenvoke funny you mention it, this was actually also something I thought about. 

I think an option somewhere for hiding/showing it would be a good idea 👀
