### ISSUE TITLE
Long test names broken into two strings with concatenations can't be run with the plugin

### ISSUE THREAD

**Issue by Tray2** [pestphp/pest-intellij#371]
I have a long test name for one of my test to describe exactly what it does, and when that caused me to scroll sideways, I decided to split the description into two strings and concatenate them for readabilities sake.

This concerns version 1.8.1

```php
it('tests that something is done and the result is satisfactory using the assertions' . 
   ' that are needed to make sure that the response is correct' , function() {
      //Test goes here
});
```

It is valid PHP and it works when running the test manually from the terminal, but when running it whit the plugin, it says that the test name is NULL, and the test is not run properly.

The work around is to use double quotes instead on the test name.

```php
it("tests that something is done and the result is satisfactory using the assertions
    that are needed to make sure that the response is correct" , function() {
      //Test goes here
});
```

Tested with just doing.

```php
it('a' . 'b', function() {
   //Test goes here
});
```

It produces the same issue.

Not a show stopper but a minor annoyance.

**Comment by olivernybroe** [comment]
@Tray2 thanks for the detailed issue. 

Interesting issue, so it seems like we have not added support for concatenated strings, this is def. something we can add support for, as long as we don't try to do more advanced stuff like with variables, sprint etc. 👀

**Comment by Tray2** [comment]
@olivernybroe No, I think we are good with just the concatenation, but some dynamic test name rendering would have been cool though, but I don't see any need for it.

**Comment by olivernybroe** [comment]
@Tray2 I have created an EAP, would be nice if you could test out if it solves your problem 👍 

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.8.3-EAP.3.zip](https://github.com/pestphp/pest-intellij/files/9604758/PEST.PHP-1.8.3-EAP.3.zip)

**Comment by Tray2** [comment]
@olivernybroe 

Installed and tested, it does recognize the name in the little tool tip now but still no go when running the test.

<img width="453" alt="Skärmavbild 2022-09-20 kl  18 45 53" src="https://user-images.githubusercontent.com/696364/191317039-ca081881-3635-4e47-943b-e089e8fa53ab.png">
<img width="461" alt="Skärmavbild 2022-09-20 kl  18 45 40" src="https://user-images.githubusercontent.com/696364/191317135-ee2e934c-2a05-4647-993f-58a30dbeeba3.png">
<img width="236" alt="Skärmavbild 2022-09-20 kl  18 46 03" src="https://user-images.githubusercontent.com/696364/191317167-c0744388-03cd-4099-adeb-dea055aa9174.png">
<img width="343" alt="Skärmavbild 2022-09-20 kl  18 48 06" src="https://user-images.githubusercontent.com/696364/191317385-4951687f-6a22-43f2-b01e-ee0bf27ae228.png">

<img width="859" alt="Skärmavbild 2022-09-20 kl  18 46 21" src="https://user-images.githubusercontent.com/696364/191317199-f296b8b1-8a1b-46fc-8f50-21536f887908.png">

**Comment by olivernybroe** [comment]
@Tray2 ah lol, must have forgotten some places 🤔 

Thanks for testing, will share a new EAP once I have found the issues here 👍

**Comment by Tray2** [comment]
@olivernybroe A small update, I can't run any pest tests from within phpstorm at all with the [PEST PHP-1.8.3-EAP.3.zip](https://github.com/pestphp/pest-intellij/files/9604758/PEST.PHP-1.8.3-EAP.3.zip)

**Comment by olivernybroe** [comment]
@Tray2 oh no 🙈

In the PhpStorm window where it runs no tests, we can see the whole command it is running, could you try and send that one to me, so we can see what is going wrong with the filter argument 👀

**Comment by olivernybroe** [comment]
I was not able to reproduce this in the new EAP 🤔 
![image](https://user-images.githubusercontent.com/5870441/191439807-19bb64cf-1b01-48a6-8d9c-0f12f2f495a1.png)

Would need to see the full command so we can troubleshoot what is wrong with the filtering in your case

**Comment by Tray2** [comment]
@olivernybroe as soon as I get back home, I will paste it here.

**Comment by Tray2** [comment]
@olivernybroe Another update.

Tested in a new project to run a test, and it worked fine, it was a regular test without concatenation.
Tried with a concatenated test as well, and it worked fine.

I think the issue is with a mismatch in the project somehow. I think it might be something that lingers from the upgrade ore some such. I will try deleting the .idea directory and see if that helps.

**Comment by Tray2** [comment]
Perfect. 🤘
