### ISSUE TITLE
How do i run dusk Browser test in phpstorm ?

### ISSUE THREAD

**Issue by chrillep** [pestphp/pest-intellij#388]
https://plugins.jetbrains.com/plugin/14636-pest/reviews#review=66033

ref:

* https://github.com/pestphp/pest-intellij/discussions/383
* https://pestphp.com/docs/plugins/laravel#laravel-dusk
* https://laravel.com/docs/9.x/dusk
* https://github.com/laravel/nova-dusk-suite

**Comment by chrillep** [comment]
> Please share a stacktraces + error message and possibly steps to reproduce.
yep ill get them. But should it work?

**Comment by olivernybroe** [comment]
No idea 🙂 

Don't know how you run dusk browser test normally or what it entails 😅

**Comment by chrillep** [comment]
> No idea 🙂
> 
> Don't know how you run dusk browser test normally or what it entails 😅

fair enough :) https://pestphp.com/docs/plugins/laravel#laravel-dusk
ill see if i can setup a demo repo

**Comment by olivernybroe** [comment]
@chrillep looking at this, it looks like the biggest difference is that you have to run dusk test via `php artisan pest:dusk`. 


However this does raise some complications, when you for example run all tests in a folder with both dusk and non dusk test in them, as that would actually require two different commands to run that 🤔 

Will all dusk test always be in the same root folder where there will only be dusk test in that folder? 
Or is it possible to mix it and do people do that? 👀

**Comment by chrillep** [comment]
all dusk tests should live inside the Browser folder

**Comment by chrillep** [comment]
but i tested it with a fresh laravel install and it now works. must be legacy setup in my current project that messes it up.

**Comment by chrillep** [comment]
steps to reproduce =)

```sh
curl -s "https://laravel.build/example-app" | bash
```

```sh
cd example-app

./vendor/bin/sail up
```

```sh
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
```

```sh
composer require --dev laravel/dusk
```

```sh
sail artisan dusk:install
```

```sh
sail dusk
```

```sh
sail test
```

```sh
composer require pestphp/pest pestphp/pest-plugin-laravel  --dev --with-all-dependencies
```

```sh
sail  artisan pest:install
```

Add
```php
use Tests\DuskTestCase;

uses(DuskTestCase::class)->in('Browser');
```
To Pest.php

```sh
php artisan pest:dusk
```

add file phpunit.dusk.xmlwith content

```xml<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Browser Test Suite">
            <directory suffix="Test.php">./tests/Browser</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

Add test file tests/Browser/ExampleTestBrowserPest.phpwith content
```php
<?php

use Laravel\Dusk\Browser;

it('has homepage', function () {
    $this->browse(function (Browser $browser) {
        $browser->visit('/')
            ->assertSee('Pest');
    });
});
```
run Pest inside phpstorm on tests/Browser folder

**Comment by chrillep** [comment]
updated description wasn't clear about this being an issue about phpstorm

**Comment by olivernybroe** [comment]
@chrillep awesome thanks for all the details. 

There should hopefully be enough information here for someone or me when I find time to work on adding this feature :) 

It is def. easier if we go with the assumption that dusk test can only live inside `browser` folder (could possibly be made configurable). 
Because then we can just say when you are trying to run a test which are in that folder, then use another command for it.

**Comment by chrillep** [comment]
> @chrillep awesome thanks for all the details.
> 
> There should hopefully be enough information here for someone or me when I find time to work on adding this feature :)
> 
> It is def. easier if we go with the assumption that dusk test can only live inside `browser` folder (could possibly be made configurable). Because then we can just say when you are trying to run a test which are in that folder, then use another command for it.

i believe i found the reason for when this works and not. The selenium server needs to be active/started when running browser tests, when and where this is done im not sure. But when running with sail, sail "automaticlly" spinns up a selenium instance as a container.

**Comment by olivernybroe** [comment]
Closing this one in favor of the discussion #383
