### ISSUE TITLE
Global Working Directory Setting

### ISSUE THREAD

**Issue by j-dexx** [pestphp/pest-intellij#392]
Hi, would it be possible to set a global working directory that would by default be inherited by each run configuration?

We have our code in src and currently I have to manually add the custom working directory to each run configuration.

**Comment by olivernybroe** [comment]
Could be possible to do yes. 

I would accept that change in the codebase :) 

However this might also be solvable in another way. Could you show your structure? Like where is your composer.json, src and tests folder and are there multiple composer.json files in your project?

**Comment by j-dexx** [comment]
If I can solve it in another way without moving anything that'd be great.

```
/project/src
/project/src/composer.json
/project/src/tests
```

Single composer.json

Using docker (not sure if that matters)

<img width="637" alt="image" src="https://user-images.githubusercontent.com/6691543/205049336-ff7c4987-5059-4f12-8b6d-da5d838c19b3.png">


```

**Comment by olivernybroe** [comment]
@j-dexx Alright, so what you wanna do should actually be possible. 

The cwd is determined based on the path of the configuration file if a custom cwd has not been set. 
![image](https://user-images.githubusercontent.com/5870441/205053707-1bf7d676-abe5-4ef3-b1b0-13981a1f21c3.png)
Go to your preferences -> PHP -> Test Frameworks and set the default configuration file path. 

You might have to go in and delete all your run configurations for this to take effect, as I am not sure it overrides the old run configurations.

**Comment by j-dexx** [comment]
Great, thanks :)

Really like the plugin.
