### ISSUE TITLE
Using test() in custom helper function, some methods have "Member has protected visibility" warning

### ISSUE THREAD

**Issue by ncla** [pestphp/pest-intellij#400]
I have the following code. It works as intended when running tests, but in PHPStorm `createMock` is underlined in red color, and hovering over it says "Member has protected visibility".

```php
function stubAsset(int $width, int $height, int $fileSize)
{
    $stubbedAsset = test()->createMock(Asset::class);
    $stubbedAsset->method('size')->willReturn($fileSize);
    $stubbedAsset->method('width')->willReturn($width);
    $stubbedAsset->method('height')->willReturn($height);
    return $stubbedAsset;
}
```

![image](https://user-images.githubusercontent.com/5507083/212126058-0a5de924-09ea-494b-8020-fa9c93c29abc.png)

I think this is a bug report for here? Let me know if not. And let me know if I can work around this somehow. Thank you!

PhpStorm about info:

```
PhpStorm 2022.3.1
Build #PS-223.8214.64, built on December 22, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-56-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1998M
Cores: 4
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    com.pestphp.pest-intellij (1.8.3)

Current Desktop: ubuntu:GNOME
```

**Comment by olivernybroe** [comment]
Thank you for a detailed issue :) 

This is unfortunately already known problem and you can follow the discussion at #60.

Unfortunately this is not something we can fix as it is a bug in phpstorm and they haven't fixed it yet.
