### ISSUE TITLE
A `[` in the test name causes 'Test framework quit unexpectedly'.

### ISSUE THREAD

**Issue by hailwood** [pestphp/pest-intellij#418]
**Describe the bug**
Same deal as #410 (apparently I name my tests weird /shrug)

**To Reproduce**
Create a test named something like `can move from a[au] to a[nz]`

**Expected behavior**
The test runs.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - IntelliJ Version: PHPStorm 2023.1 EAP
 - Plugin Version 1.9.1-EAP.1

**Additional context**
Entire command
```
pest --teamcity --configuration /app/phpunit.xml /app/tests/Feature/StreamProfileUpdater/FromFuneralHomeExistingTest.php "--filter=/^(P\\)?Tests\\Feature\\StreamProfileUpdater\\FromFuneralHomeExistingTest::it\scan\smove\sfrom\sa[au]\sto\sa[nz](\swith\s(data\sset\s\".*\"|\(.*\))(\s\/\s(data\sset\s\".*\"|\(.*\)))*(\s#\d+)?)?$/"
```

Note that if I replace the `[` and `]` with `(` and `)` respectively so we end up with `can move from a(au) to a(nz)` the test runs.
The only difference in the commands is that rather than `[` or `]` we end up with `\(` and `\)`.
I attempted to replace the `[` and `]` with `\[` and `\]` but no difference.

**Comment by olivernybroe** [comment]
Sorry, completely forgot about this. It somehow fixed it for me by just escaping them. 
Can you try out this EAP to check if it also works for you? 
[PEST PHP-1.9.3-EAP.2.zip](https://github.com/pestphp/pest-intellij/files/11330409/PEST.PHP-1.9.3-EAP.2.zip)

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
