### ISSUE TITLE
Add ability to select coverage engine 

### ISSUE THREAD

**Issue by dmason30** [pestphp/pest-intellij#42]
The addition of coverage support works great thanks! 

Is there scope to add the same 'Preferred coverage engine' drop down as seen on the PHPUnit config below which changes the arguments added when running tests with coverage?

More importantly, generally you will have the library installed but disabled by default in the PHP setup. For PHPUnit one of these arguments enable whichever coverage engine is selected when running tests. 

The plugin is enabling Xdebug along with other args even when not using as was discussed in the original issue (#33). Also means if you are using PCov or PHPDBG then you need to enable that in your PHP config before running tests or add the enabled args for your coverage engine to the additional arguments field.

![image](https://user-images.githubusercontent.com/20278756/89412826-a0cd7980-d71f-11ea-9534-3ea555725fb5.png)

**Comment by olivernybroe** [comment]
I am trying to figure out a way to add support for this, without having to build it from scratch.

However it looks like it was custom-made by IntelliJ for phpunit, not for all test runners. Hopefully I can find a way to do it easily or we can ask IntelliJ if they would make it available for usage in other test runners

**Comment by olivernybroe** [comment]
So right now the problem is, I am having a tough problem with adding in the dropdown without doing a bunch of reflection which I would rather not as that is pretty unstable.

I'll try and research further, else I'll have to involve JetBrains and hope they have a solution

**Comment by olivernybroe** [comment]
So I figured out how to add the dropdown with little reflection, however now I have to figure out the command for running the different tools in the correct way.

I think I'll start with just adding support for one extra and when/if there is demand for more engines, then I'll add that. 

@dmason30 Which one is it you are missing support for and how do you run it correctly? Only used xdebug myself

**Comment by dmason30** [comment]
Great news! Thanks for the hard work. 

I us `PCov` believe you just need `-dpcov.enabled=1` added to the command instead of what is added specifically for xdebug. Installing the pcov php extension should be pretty painless.
