### ISSUE TITLE
Plugin::uses should include class on this variable

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest-intellij#43]
Hey Friends, huge thanks for your work on this, going to describe some issues I found, fell free to create / split this into multiple issues later:

1. Plugins uses seems to not be detected, here is the plugin livewire code that should inject a new method into `$this` variable:
```
//  the plugin code
Plugin::uses(InteractsWithLivewire::class);
```

But no autocompletion:
<img width="356" alt="Screenshot 2020-08-05 at 21 23 37" src="https://user-images.githubusercontent.com/5457236/89460457-3a1d7f80-d762-11ea-9646-1bd1cc219e47.png">

2. Also, after the `it()` we don't get autocompletion like the this. Here I am using the Laravel test case, and the `it()` don't returns a test case from laravel:

<img width="910" alt="Screenshot 2020-08-05 at 21 26 17" src="https://user-images.githubusercontent.com/5457236/89460515-4f92a980-d762-11ea-90f5-5b8b6d78fc1a.png">

**Comment by adelf** [comment]
1. `Plugin::uses` isn't supported yet.
2. Didn't know about this feature. So, `it` and `test` functions result should have the same type as `$this` variable there?

**Comment by nunomaduro** [comment]
> Plugin::uses isn't supported yet.

Alright.

> Didn't know about this feature. So, it and test functions result should have the same type as $this variable there?

@adelf, its more like: `it` and `test` functions should return their type plus the `$this` type. Like an union.

**Comment by adelf** [comment]
1. Will be not very easy to implement... But it's possible to make something like Settings window where users can ask to collect all PEST plugins there. and then they will be added to each $this
2. It's easier than 1. Could be added soon.

**Comment by olivernybroe** [comment]
@adelf The `Plugin::uses` is basically used in plugins to pest which are coming via composer. So we might also be able to do some auto triggering of the cache for that when composer.lock is changed?

**Comment by hackel** [comment]
FYI, a quick and dirty hack to get completion for higher order tests is to add `@mixin \Tests\TestCase` (or whichever testcase you use most) to the annotation of `\Pest\PendingObjects\TestCall`.  This is what laravel-ide-helper does for the Laravel query builders and is supported natively by PHPStorm.

**Comment by adelf** [comment]
@hackel it will be fixed in the next plugin version. As far I understand this base class can be configured via `uses()` calls, so it will be too dirty to set some static mixin there :)

**Comment by olivernybroe** [comment]
@adelf is all of this implemented now so we can close this issue?

**Comment by adelf** [comment]
plugin::uses isn’t implemented yet.
