### ISSUE TITLE
report

### ISSUE THREAD

**Issue by EdsonJunio** [pestphp/pest-intellij#445]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - IntelliJ Version: [e.g. PHPStorm 2022.3]
 - Plugin Version [e.g. 1.9.1]

**Additional context**

**Comment by olivernybroe** [comment]
What am I supposed to do with this?
