### ISSUE TITLE
No matter how much I run this test, it passes, but the arrow doesn't turn into a checkmark

### ISSUE THREAD

**Issue by danielh-official** [pestphp/pest-intellij#451]
**Describe the bug**
None of my Pest tests are showing a checkmark when they pass or an X when they fail. They just remain an arrow.

**To Reproduce**
1. Download the plugin like normal
2. Ensure you're on Laravel 10 and Php 8.2
3. Try doing this on a Macbook Pro
4. Create an Example Pest test

```php
<?php

test('that true is true', function () {
    expect(true)->toBeTrue();
});
```

**Expected behavior**
It should pass but not show a checkmark at the left.

**Screenshots**

Gallery: https://imgur.com/a/hrQ7uy1

**Desktop (please complete the following information):**
 - OS: Mac 13.3.1 (22E261)
 - IntelliJ Version:
```
PhpStorm 2023.1
Build #PS-231.8109.199, built on March 29, 2023
Runtime version: 17.0.6+10-b829.5 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.shz.anonymous-progress-bar (1.0.2)
    com.github.copilot (1.2.5.2507)
    com.intellij.ideolog (203.0.30.0)
    com.trickbd.CodeGPT (1.03)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.2.1)
    org.endpointdeps.EndpointDependencies (1.3)
    dev.nybroe.collector (0.4.0)
    net.rentalhost.plugins.laravel.hammer (0.2.1)
    com.pestphp.pest-intellij (1.9.2)
    com.github.googee.laravelbuilder (0.3.0)
    com.laravel_idea.tailwind (1.4.1)
    com.smartapplications.stormsections (1.5.2)
    izhangzhihao.rainbow.brackets (2023.2.7)
    dev.ekvedaras.laravelquery (4.0.2)
    fr.adrienbrault.idea.symfony2plugin (2022.1.246)
    com.niclas-van-eyk.laravel-make-integration (3.5.0)
    com.dmarcotte.handlebars (231.8109.91)
    nz.hailwood.inertiajs (0.1.8)
    com.laravel_idea.plugin (7.0.3.231)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-231)
```
 - Plugin Version: 1.9.2

**Additional context**

This is the line that's passed in the test runner (second image in Imgur gallery):

`/usr/local/Cellar/php/8.2.4/bin/php /Users/{user}/Repositories/{root}/{project}/vendor/pestphp/pest/bin/pest --teamcity --configuration /Users/{user}/Repositories/{root}/{project}/phpunit.xml /Users/{user}/Repositories/{root}/{project}/tests/Unit/ExampleTest.php "--filter=/^(P\\)?Tests\\Unit\\ExampleTest::that\strue\sis\strue(\swith\s(data\sset\s\".*\"|\(.*\))(\s\/\s(data\sset\s\".*\"|\(.*\)))*(\s#\d+)?)?$/"
`

Link to forum post: https://intellij-support.jetbrains.com/hc/en-us/community/posts/11162661050258-Pest-success-checkmark-result-not-showing-in-PhpStorm-IDE

**Comment by olivernybroe** [comment]
Thanks for adding details. I can confirm I experienced the same on 2023.1 and in 2022.3 phpstorm. 

Here is an EAP which hopefully should fix this issue for you, please confirm and we can release a new version with it :) 
[PEST PHP-1.9.3-EAP.1.zip](https://github.com/pestphp/pest-intellij/files/11330253/PEST.PHP-1.9.3-EAP.1.zip)

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

**Comment by olivernybroe** [comment]
Closing issue and will reopen if fix doesn't work :)

**Comment by danielh-official** [comment]
It's working now.

The only thing I would add (as a feature tweak) is that the top "Run All" arrow on the file turns into a checkmark if all the tests pass, a yellow warning icon if at least one test fails, or a red X if all tests fail.

Right now, it's staying as a double arrow pointing right.

**Comment by olivernybroe** [comment]
@danielh-official Sounds great :) For reference this is the file you would need to do the changes in. 
https://github.com/pestphp/pest-intellij/blob/main/src/main/kotlin/com/pestphp/pest/PestTestRunLineMarkerProvider.kt
