### ISSUE TITLE
This test did not perform any assertions

### ISSUE THREAD

**Issue by scheMeZa** [pestphp/pest-intellij#456]
**Describe the bug**
When writing a test with an assertion and the test fails, instead of showing that it has failed, pest says "This test did not perform any assertions".
![image](https://github.com/pestphp/pest-intellij/assets/7773361/fe5ba70d-fd7d-4e36-a821-f7cd49d1fda8)

**To Reproduce**
1. Go to the failing test
2. Run using PHPStorm's RUN:
![image](https://github.com/pestphp/pest-intellij/assets/7773361/333bc42a-46ae-4604-b19a-8ca17fa0cd37)
4. See "This test did not perform any assertions"

**Expected behavior**
I expect PHPStorm to highlight test with red, indicating the test has failed. To be able to click on the failed test and navigate to it in PHPStorm.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows WSL
 - IntelliJ Version: 2023.1.1
 - Plugin Version 1.9.2

**Additional context**
Running `php artisan test` works, but running the tests in PHPStorm does not.

**Comment by olivernybroe** [comment]
@scheMeZa a quick glance at this, it seems like it might be related to https://github.com/pestphp/pest/issues/800 👀

**Comment by scheMeZa** [comment]
![image](https://github.com/pestphp/pest-intellij/assets/7773361/129c7bf9-081f-45a4-ba96-3bbab153d21b)
![image](https://github.com/pestphp/pest-intellij/assets/7773361/86fde71b-fc82-4e4e-9d83-23284d16c2f9)

**Comment by scheMeZa** [comment]
![image](https://github.com/pestphp/pest-intellij/assets/7773361/7d3820e7-a17e-420b-8118-c696c28d5fd4)
![image](https://github.com/pestphp/pest-intellij/assets/7773361/5e1d549a-7cda-45a4-80bc-40acd6ed797d)

**Comment by scheMeZa** [comment]
> @scheMeZa a quick glance at this, it seems like it might be related to [pestphp/pest#800](https://github.com/pestphp/pest/issues/800) 👀

Thanks for the quick reply.
I've added screenshots of my complete setup above, to see if it helps.

**Comment by olivernybroe** [comment]
@scheMeZa once the other issue has been fixed, I'll ask you for a retry and see if it fixes your problem here also (which I think is the same) and then we hopefully should be able to close this one 👍

**Comment by olivernybroe** [comment]
Closing this one as a fix in pest should have landed now 👀 try updating pest itself and see if still an issue. 

If it is, I'll reopen 👍
