### ISSUE TITLE
Can't rerun failed tests inside PHPStorm 

### ISSUE THREAD

**Issue by craigpotter** [pestphp/pest-intellij#471]
**Describe the bug**
Ever since upgrading my repo to using PestPHP v2, I can no longer return failed tests. 
Instead I get the following message. 

```bash 
Failed finding any tests to rerun Rerunning support was first added in Pest v0.3.5 
```

**To Reproduce**
1. Create a simple test in with two or more tests. One should fail. 
```php
test('this test should pass', function () {
    $this->assertTrue(true);
});

test('this test should fail', function () {
    $this->assertTrue(false);
});

test('this test should also pass', function () {
    $this->assertTrue(true);
});
``` 

2. Run the entire file
![CleanShot 2023-06-19 at 15 33 09](https://github.com/pestphp/pest-intellij/assets/1442635/542abbe6-e616-4200-88a5-3532e40009a1)

3. Check the output and click rerun failed test buttons 
![CleanShot 2023-06-19 at 15 33 31](https://github.com/pestphp/pest-intellij/assets/1442635/1cae3c11-1832-4e93-a471-0c66c9d8a96d)

4. Note that all 3 tests are rerun and notification pops up 
![CleanShot 2023-06-19 at 15 36 08](https://github.com/pestphp/pest-intellij/assets/1442635/845cf3d7-1bb9-4195-8a39-71f897542eb1)

**Expected behavior**
It should just rerun the failed test only. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.4 
 - IntelliJ Version: PHPStorm 2023.1.2
 - PestPHP Version: 2.6.1
 - Plugin Version: 1.10.1

**Additional context**

**Comment by olivernybroe** [comment]
This error is shown when filter finds no tests. 

There was recently a bug in pest which made filter not work anymore. 

Can you try updating your pest in php to the newest version and see if it is still an issue. 

If it is, I'll re-open the ticket. 👍

**Comment by craigpotter** [comment]
Thanks @olivernybroe, 

I've just updated pest to the latest version and can still confirm it is still a problem

<img width="582" alt="CleanShot 2023-06-20 at 19 21 34@2x" src="https://github.com/pestphp/pest-intellij/assets/1442635/2c906164-6433-42ec-8352-419a5a2380c5">

**Comment by olivernybroe** [comment]
I have confirmed that I was able to reproduce.

**Comment by Lukasss93** [comment]
any news about the fix?

**Comment by olivernybroe** [comment]
A fix for this will be included in next release.
