### ISSUE TITLE
Pest not displaying results of each test (maybe?)

### ISSUE THREAD

**Issue by nexxai** [pestphp/pest-intellij#472]
**Describe the bug**
When I run the test suite from within PHPstorm, it shows me the progress bar and the results of the run but I'm really used to running it in the terminal and seeing each test as it passes or fails.  I've seen other screenshots where it *does* work for other people so I'm assuming it has something to do with my config, but I literally just started using PHPstorm so I don't know what I could have broken to make it do this.

**To Reproduce**
1. Run the test suite
2. Look at the results

**Expected behavior**
Something similar to:
```
...

   PASS  Tests\Feature\UpdatePasswordTest
  ✓ password can be updated                                                                                                                    0.12s
  ✓ current password must be correct                                                                                                           0.18s
  ✓ new passwords must match                                                                                                                   0.18s

  Tests:    7 skipped, 167 passed (338 assertions)
  Duration: 13.51s
```

**Screenshots**
<img width="1501" alt="Screenshot 2023-06-20 at 4 32 23 PM" src="https://github.com/pestphp/pest-intellij/assets/4316564/4ade4064-9b28-4a72-8298-6b16763ea571">

**Desktop (please complete the following information):**
 - OS: macOS Ventura (up to date)
 - IntelliJ Version: PhpStorm 2023.2 EAP Build #PS-232.7754.72
 - Plugin Version: 1.10.1

**Additional context**
none that I can think of

**Comment by olivernybroe** [comment]
This is on purpose. 

We do not print out a lot of things to not bloat the output.

If you would like to see all passed tests, you can clock the check box icon in the left side of the test output 🙂

By default PhpStorm chooses to hide passed tests.

**Comment by nexxai** [comment]
Amazing, thank you for confirming!
