### ISSUE TITLE
Errors encountered while running tests using the plugin launch Google Chrome instead of default browser

### ISSUE THREAD

**Issue by ramsey** [pestphp/pest-intellij#483]
**Describe the bug**
When the Pest plugin encounters an error, it launches a Google Chrome browser instead of my system default browser, Safari.

**To Reproduce**
1. Create a Pest test script at `tests/describe-block.php` and use the following test code:
    ```php
    <?php
    describe('described block', function (): void {
        it('runs the tests')
            ->expect(true)
            ->toBeTrue();
    });
    ```
    _(For now, ignore the fact that this uses the new `describe()` function in Pest 2.9. That's not what this issue focuses on. Clearly, the plugin doesn't recognize the `describe()` function yet, and that's what causes the error, but this issue is about launching a web browser that is not the system default.)_

2. In PhpStorm, I see this rendered with a green arrow next to the test, which I can click on to run the test:  <img width="595" alt="Screenshot 2023-07-26 at 18 51 30" src="https://github.com/pestphp/pest-intellij/assets/42941/7ed223ef-7419-4432-a64d-8c4bf36d178f">

3. When I click the green arrow, PhpStorm launches a Google Chrome browser window and changes focus to it. In the browser window is the following error:

        Fatal error: Uncaught Error: Call to undefined function describe() in
        /path/to/tests/described-block.php on line 3

    The browser address bar shows the address http://localhost:63343/path/to/tests/described-block.php?_ijt=XXXXXXXXXXXXXXXXXXXXXXXXXX

4. The error is that Google Chrome launches instead of my system default browser, Safari.

**Expected behavior**
If the plugin is supposed to launch a web browser for this error, I expect it to launch the system default browser, Safari.

**Screenshots**
I have PhpStorm set to use the "System default" as its default browser:
<img width="656" alt="Screenshot 2023-07-26 at 18 56 17" src="https://github.com/pestphp/pest-intellij/assets/42941/d5677d76-ab98-4af2-b511-646c71cfb6d3">

And I have Safari set as the default browser:
<img width="827" alt="Screenshot 2023-07-26 at 19 06 53" src="https://github.com/pestphp/pest-intellij/assets/42941/9b3afecc-3809-47d3-9805-2caff0e60d00">

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1 (c)
 - IntelliJ Version: PhpStorm 2023.1.3
 - Plugin Version: 1.10.1

**Comment by olivernybroe** [comment]
So what is happening here is actually not that the plugin is trying to show the error in the browser.
The green arrow works the way that it tries to find all possible run configuration options for the specified element in the AST tree.

Usually you would see Pest as the option there, however because we don't support `describe` blocks it does not show #462. 
What happens then is IntelliJ is trying to look through all other possible run configurations and find the default php run configuration which is open the file in the browser with a light weight web server for running the php code.

**Comment by olivernybroe** [comment]
Might be related to this bug report https://youtrack.jetbrains.com/issue/WI-53235/PHP-Web-Page-default-browser-always-has-Chrome-icon

**Comment by ramsey** [comment]
Thanks for the reply!
