### ISSUE TITLE
Autocompletion not available on expectations

### ISSUE THREAD

**Issue by eleftrik** [pestphp/pest-intellij#489]
**Describe the bug**
Apparently, PEST plugin doesn't show autocompletion anymore on expectations.

**To Reproduce**
1. Inside a PEST test, write an expectation, For example:

```php
test('app architecture', function () {
    expect('App\\')
        ->

    // or


   expect(true)
      ->
});
```

2. Press CTRL+space (on MacOS) to see autocompletion
3. Autocompletion is not available

**Expected behavior**
The IDE should list available methods.

Tried 

**Screenshots**

<img width="748" alt="image" src="https://github.com/pestphp/pest-intellij/assets/6959298/b75893f7-911a-4a4c-ba44-e80688763b60">

**Desktop**
- OS: MacOS
- PhpStorm 2023.2 Build #PS-232.8660.205, built on July 28, 2023
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.7
- Plugin Version: com.pestphp.pest-intellij (1.10.1)
- Composer packages:
    - pestphp/pest v2.9.4
    - pestphp/pest-plugin ^2.0.1
    - pestphp/pest-plugin-arch ^2.2.2
    - php ^8.1.0

Thank you

**Comment by bonge-ian** [comment]
I also had the same experience, with pest version ^2.

However while on another project, on version 1, auto-completion is provided
Below is whilst using the following pest version:

- pestphp/pest ^1.20,

- pestphp/pest-plugin-laravel ^1.1,

![Screenshot (1)](https://github.com/pestphp/pest-intellij/assets/35810849/21a28a91-fb0e-4f39-835c-e6fe16518431)

**Comment by olivernybroe** [comment]
Hmm, this seems like a PhpStorm bug 🤔 

I tried disabling the Pest plugin as autocompletion for expectations which are not extend expectations should work without, but it does not. 

It seems to be a bug in phpstorm when using generics in `@mixin` phpdocs.
Try removing the generic from the `@mixin` in `Expectation` class and see if it works. It does so for me.

**Comment by olivernybroe** [comment]
Closing this as it seems like it is purely related to phpstorm :)
I have added a comment in the issue about generics support in mixin.
https://youtrack.jetbrains.com/issue/WI-69638/Support-Generics-Type-in-mixin#focus=Comments-27-7997004.0-0
