### ISSUE TITLE
Tests within describe blocks ran via phpstorm do not show output

### ISSUE THREAD

**Issue by Riley19280** [pestphp/pest-intellij#490]
**Describe the bug**
Ran a test in a `describe` block by pressing the green arrow
![image](https://github.com/pestphp/pest-intellij/assets/14127031/737531e7-b1e2-4050-8d2d-820fd69e26a1)

Then no output is show in phpstorm

![Screen Shot 2023-08-15 at 12 34 10 AM](https://github.com/pestphp/pest-intellij/assets/14127031/27888ab2-94d1-4b18-a45f-9e5c7ef142cc)
**Expected behavior**

Expected to see test output like so when code is not in a describe block
![image](https://github.com/pestphp/pest-intellij/assets/14127031/798521a7-27d7-40bb-a4cf-0662c0a5f092)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.5
 - IntelliJ Version: [PhpStorm 2022.3.3
 - Plugin Version 1.9.2

**Comment by davideprevosto** [comment]
As per the following thread, it seems you can avoid to use describe() or PR a fix at the moment.
https://github.com/pestphp/pest-intellij/discussions/462

**Comment by olivernybroe** [comment]
@davideprevosto yep, currently the only workarounds are avoid using it, or run the whole file every time 👍
