### ISSUE TITLE
[Bug]: Property declared dynamically, this is deprecated starting from PHP 8.2

### ISSUE THREAD

**Issue by aon2003** [pestphp/pest-intellij#496]
### What Happened

I'm using PHP 8.2 and PEST 2.16.
I have the following test file:
```php
<?php

declare(strict_types=1);

use App\Models\User;
use Laravel\Dusk\Browser;

beforeEach(function () {
    // TODO: Dynamic property declaration is deprecated.
    $this->user_id = User::where('email', 'sales@jump.bg')->first()->id;
});

it('has needed role to view a page', function (string $route, array $params) {
    $this->browse(function (Browser $browser) use ($route, $params) {
        $browser
            ->loginAs($this->user_id)
            ->visitRoute($route, $params)
            ->assertDontSee(trans('errors.403'));
    });
})->with('role_allow_routes')->group('role', 'roles');

it("doesn't have needed role to view a page", function (string $route, array $params) {
    $this->browse(function (Browser $browser) use ($route, $params) {
        $browser
            ->loginAs($this->user_id)
            ->visitRoute($route, $params)
            ->assertSee(trans('errors.403'));
    });
})->with('role_deny_routes')->group('role', 'roles');
```

For now, everything works fine, but this method of dynamically declaring properties is deprecated from PHP 8.2 and may be totally removed in the future (`$this->user_id = User::where('email', 'sales@jump.bg')->first()->id;`).

Will there be another way of using one variable for every test in a test file?

### How to Reproduce

Make a simple Laravel 10 app with PEST 2 and try to declare property dynamically in a PEST hook.

### Pest Version

2.16.0

### PHP Version

8.2.9

### Operation System

Linux

**Comment by olivernybroe** [comment]
Seems like PhpStorm has made changes to their internals, it did not use to report this 😅


It might be worth checking if we can either add the property to the test case class or silence this inspection here.

**Comment by davideprevosto** [comment]
I personally have had the same  since I started using Pest, many months ago.

**Comment by olivernybroe** [comment]
A fix for this will be part of next release.
