### ISSUE TITLE
Add autocompleting for $this

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#5]
Right now when using `$this` in the test closure it cannot autocomplete the method.

The issue is about adding autocompletion for `$this`.

Additional methods can be added to `$this` by using `uses`, see [docs]( https://pestphp.com/docs/underlying-test-case/).

Also all plugins use the following syntax to register them `Plugin::uses(InteractsWithLivewire::class);`

- [x] For basic phpunit test
- [x] For local `uses`
- [x] For plugin `Plugin::uses`

**Comment by nunomaduro** [comment]
Can't wait to have this.

**Comment by olivernybroe** [comment]
There are now support for autocompletion, but hardcoded to use phpunit basic test case only. 

Thanks @adelf!

**Comment by nunomaduro** [comment]
@olivernybroe updated your comment on the top. Works for you?

**Comment by BertvanHoekelen** [comment]
Really loving the PR of @olivernybroe. Just what I needed to get started on migrating my current test suite. I am wondering if it will be possible that it also understands variable docblocks like `$this->foo3`:
```php
beforeEach(function () {
    $this->foo1 = $this->mock(Foo::class);

    $this->foo2 = Mockery::mock(Foo::class);

    /* @var \Mockery\MockInterface|Foo foo3 */
    $this->foo3 = $this->mock(Foo::class);
});

test('has autocomplete', function () {
    $this->foo1->bar(); // No autocomplete, probably because the closure is unaware of the TestCase as described in this ticket.

    $this->foo2->bar(); // Autocomplete working :heart: 

    $this->foo3->bar(); // No autocomplete
});
```

**Comment by adelf** [comment]
I know how to fix `foo1` case. I hope it will be fixed soon.
`foo3`'s phpDoc isn't correct. Better to create a PhpStorm metafile for `mock` method, Like here - https://github.com/tomasfejfar/phpunit-phpstorm-meta and it also will be fixed by the first fix.

**Comment by BertvanHoekelen** [comment]
You’re absolutely right about that `@var`, my bad. So used to assign classes to variables if phpstorm doesn't understand.
After some trying `foo1` can be fixed using: 
```
beforeEach(function () {
    /* @var \Tests\TestCase $this */

    $this->foo1 = $this->mock(Foo::class);
    $this->foo2 = Mockery::mock(Foo::class);
});

test('has autocomplete', function () {
    $this->foo1->bar(); //Autocomplete working :)
    $this->foo2->bar(); // Autocomplete working :)
});
```

Again thanks for this feature, you guys are killing it!

**Comment by adelf** [comment]
```
/* @var \Tests\TestCase $this */
```
I'll fix this soon :)
