### ISSUE TITLE
[Feature Request] Context menu on "Test Results"

### ISSUE THREAD

**Issue by nuernbergerA** [pestphp/pest-intellij#57]
The PHPUnit Plugin has a nice context menu with some handy features which I miss here:
- Re-run a singe test even in debug mode
- Jump to Source is also the default behavior on double-clicking a row

![image](https://user-images.githubusercontent.com/13331388/91481034-1bfbf880-e8a4-11ea-9b02-07acce5b10a2.png)

Thanks for all the work you guys have put into it so far!

**Comment by olivernybroe** [comment]
The jump to source feature will actually work when https://github.com/pestphp/pest/pull/141 is merged 👍 

The reason we can't get it to work right now is because the test data from pest is giving invalid paths to where the source code is. That pr fixes it

**Comment by olivernybroe** [comment]
@nuernbergerA Could you please update your PestPHP to `^0.3.4` and report back if this works now. It should work 👍
