### ISSUE TITLE
PHPUnit assertions not shown in autocomplete suggestions

### ISSUE THREAD

**Issue by ragulka** [pestphp/pest-intellij#62]
When writing regular PHPUnit tests, all the available PHPUnit assertions are suggested:

<img width="623" alt="CleanShot 2020-09-04 at 14 19 13@2x" src="https://user-images.githubusercontent.com/593267/92234265-62f87800-eeba-11ea-8f7a-056f0f576c02.png">

However, when using the `$this->assert...` syntax in PEST tests, none of them show up:

<img src="https://cdn-std.droplr.net/files/acc_880227/U7kAoi">

**Comment by olivernybroe** [comment]
This should have been fixed now. I'll release a new alpha version tomorrow :)
