### ISSUE TITLE
Run context for directories but not files or methods

### ISSUE THREAD

**Issue by adamthehutt** [pestphp/pest-intellij#63]
I'm not sure if I'm doing something wrong, but I'm only able to run Pest on directories, not on files or individual tests. I'm 95% sure this _used to work_ with this plugin, so perhaps something changed in a recent release?

When I right-click a tests directory, the "Run" option includes PHPUnit and Pest.

When I right-click a test file or a test method/function, PHPStorm doesn't seem to recognize it as a Pest test. The only option is to run it as a "PHP script", which of course doesn't work.

The plugin version installed is 0.4.0-alpha.3.

**Comment by olivernybroe** [comment]
Hmm could you share a pest file you are trying to run this way? 

And does it work if you go to your run configurations and create a new pest run configuration that points to that file?

**Comment by adamthehutt** [comment]
In trying to create a sample for you, I think I figured out the issue. It's the namespace declaration at the top of the file. If I remove it, then PHPStorm recognizes it instantly as a Pest test. If there's a namespace, though, it will only consider a PHPUnit test or a PHP script.

I realize namespaces aren't usually used with pest tests, but I have a huge test suite and the pests tests sometimes need helper functions, so I'm trying to avoid name collisions. Thanks for your help!

**Comment by olivernybroe** [comment]
Ah thanks for debugging this. 

In the latest alpha we added in that it should not look for tests throughout the whole file for making everything faster. 

So for example if you tests are inside an if condition we won't find them.

But looks like our condition don't work when having a namespace. I'll into this :)

**Comment by olivernybroe** [comment]
https://github.com/pestphp/pest-intellij/releases/tag/v0.4.0-alpha.4
A new version has just been added which fixes this :) 

You can download it from github or wait a day and it's available in marketplace

**Comment by adamthehutt** [comment]
Fantastic, thank you!

**Comment by olivernybroe** [comment]
Hope it solves your issues :)
