### ISSUE TITLE
Higher order tests without description don't have the pest icon

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest-intellij#7]
<img width="651" alt="Screenshot 2020-06-28 at 20 24 28" src="https://user-images.githubusercontent.com/5457236/85955249-82849900-b97d-11ea-83be-09b7f9ef7613.png">

**Comment by olivernybroe** [comment]
One thing we need to figure out is how to generate the name of the test, when it's without description.

@nunomaduro What is the current approach for this so we can mimic it?

**Comment by nunomaduro** [comment]
@olivernybroe You need the test name so you can filter it?

**Comment by olivernybroe** [comment]
@nunomaduro Exactly, so if you only wanna run that test, I need the name for it.

**Comment by nunomaduro** [comment]
@olivernybroe I think we may want to hold this for now. Having autocomplete on `$this` is like super crucial at the moment.

**Comment by olivernybroe** [comment]
On hold https://github.com/pestphp/pest/issues/126

**Comment by olivernybroe** [comment]
Closing here as the blocking pest issue was closed
