### ISSUE TITLE
Add support for rerunning failed phpunit tests

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#70]
From the discussion in #35, we realised that the plugin does not support rerunning failed phpunit tests when pest and phpstorm tests are running together.

**Comment by roman-eonx** [comment]
This issue is still actual, right? Rerunning failed tests is not working for us in PhpStorm 2021.3.1 with the 1.3.0 plugin version.

**Comment by olivernybroe** [comment]
@roman-eonx yep, this is still an issue, rerunning failed phpunit tests has not been added support for yet 😞

**Comment by roman-eonx** [comment]
Are there any ideas on how to add it? Is it something fundamental/complex or just a matter of a minor fix?

**Comment by olivernybroe** [comment]
@roman-eonx I don't think it's the most complex, but also not a matter of minor fix. 

Basically we have a list of all the test names that failed, we then translate that to a location in the code, so we know what line the test failed on. Then we take the test and translate that into an argument which we can supply to the `filter` method.

it's a long time since I actually looked into this, so I cannot remember which parts of this is implemented with phpunit and which aren't. I know that the last step is not, as phpstorms code for making that translation is private, so I cannot just reuse it, but have to rewrite it.

Most of the logic for this is happening here https://github.com/pestphp/pest-intellij/blob/main/src/main/kotlin/com/pestphp/pest/configuration/PestRerunFailedTestsAction.kt#L47

**Comment by roman-eonx** [comment]
@olivernybroe and inability to go to the failed test in the code from the results panel is related to this issue/feature as well?
![image](https://user-images.githubusercontent.com/48544017/150132586-4498fedb-55c7-4769-881d-30ae6db40a33.png)

**Comment by rshaw5** [comment]
Would love to see this in a future update.

**Comment by olivernybroe** [comment]
> @olivernybroe and inability to go to the failed test in the code from the results panel is related to this issue/feature as well?
> ![image](https://user-images.githubusercontent.com/48544017/150132586-4498fedb-55c7-4769-881d-30ae6db40a33.png)
> 

It should not be. I did recently solve a bug related to navigation to tests, it is still in the EAP.

**Comment by olivernybroe** [comment]
@rshaw5 no updates on this. 

I am not working on this myself as I don't use phpunit. Feel free to submit a PR though. 

Might work on it at some point, but not really a priority for me.

**Comment by olivernybroe** [comment]
Closing this issue as I have no interest in doing this myself. 

Pr's are welcome!

**Comment by yipeecaiey** [comment]
for anyone else finding this thread...and working on a Laravel project...[Laravel Shift Pest Converter](https://laravelshift.com/phpunit-to-pest-converter) can do a lot of the legwork for converting all your phpUnit tests to PestPHP.  For me that was a far simpler option than sorting out a fix for this plugin!

**Comment by olivernybroe** [comment]
@yipeecaiey This plugin is now managed by phpstorm team instead, they prob. have a bigger interest in fixing this. 

I would suggest you to open an issue in YouTrack for their team to be aware :) 
https://youtrack.jetbrains.com/issues/WI 

Tagging in @isfedorov for awareness

**Comment by yipeecaiey** [comment]
https://youtrack.jetbrains.com/issue/WI-76232/Rerun-Failed-Tests-does-not-work-when-tests-contain-both-phpunit-and-pest-tests
