### ISSUE TITLE
Output in PHPStorm looks like phpunit, not pest

### ISSUE THREAD

**Issue by Synchro** [pestphp/pest-intellij#71]
I have set up a pest test running as per the docs, and when it runs inside PHPStorm it looks like "regular" phpunit:

![image](https://user-images.githubusercontent.com/81561/94270267-1693db80-ff40-11ea-84fd-d41f298e9cb4.png)

But when I run it on a command line it produces pretty pest output:

![image](https://user-images.githubusercontent.com/81561/94270409-44792000-ff40-11ea-8ec9-a51c82587555.png)

I assume the difference is in the `--teamcity` output option, but can I get the pretty pest output in PHPStorm? Or is the teamcity format output needed to provide source links?

**Comment by Synchro** [comment]
I also see that phpunit reports 0 assertions; I'm using pest expectations – are the assertions via that not visible to phpunit?

**Comment by olivernybroe** [comment]
Thanks, this is exactly as you said caused by the teamcity printer. Actually to fix this, we do not have to change any code in the plug-in, it should all be changed in pest core. And more m more directly in the teamcity printer. 


Where does it report 0 assertions? :)

**Comment by Synchro** [comment]
Thanks. "0 Assertions" is at the bottom of the first screen shot.

**Comment by olivernybroe** [comment]
@Synchro Could you cross-post this in pest repository instead? 
As the code is actually not in the plugin but in pest 👍

**Comment by Synchro** [comment]
Done. Closing here.
