### ISSUE TITLE
PHPStorm plugin issue, when using Pest in a 'non-standard environment'

### ISSUE THREAD

**Issue by NickSdot** [pestphp/pest-intellij#73]
I tried PEST and the plugin for PhpStorm in the last few days and I like it very much. Thanks for your work!

In one of my Laravel projects the directory structure is a bit different as the common 'standard'.  I ended up with the following error when running tests directly in PhpStorm.

### Error

> Testing started at 13.50 ...
> /usr/local/Cellar/php/7.4.11/bin/php /Users/username/Development/valet/projectX/libraries/vendor/pestphp/pest/bin/pest --teamcity --configuration /Users/username/Development/valet/projectX/libraries/phpunit.xml /Users/username/Development/valet/projectX/tests/Unit/ExamplePestTest.php --filter=/^P\\Tests\\Unit\\ExamplePestTest::it\sasserts\strue\sis\strue(\swith\s\(.*\)(\s#\d+)?)?$/
> 
>    Pest\Exceptions\FileOrFolderNotFound 
> 
>   The file or folder with the name `composer.json` not found.
> 
> Process finished with exit code 1

This seems to happen because `ValidatesEnvironment()` in `bin/pest` is searching for `composer.json in` in `/Users/username/Development/valet/projectX/` instead of `/Users/username/Development/valet/projectX/libraries/`

### Notes

- Running tests with PHPUnit trough Console works ✅
- Running tests with PHPUnit trough PhpStorm works ✅
- Running tests with PEST trough Console works ✅
- Running tests with PEST trough PhpStorm **works NOT** ❌

### Project structure

> \ Some Directories
> |        |
> |        |_  ///
> | 
> \ Laravel (libraries)
> |        |
> |        |_ app
> |        |_ config
> |        |_ database
> |        |_ storage
> |        **|_ vendor**
> |        **|_ composer.json**
> |        **|_ phpunit.xml**
> |
> \ Some Directories
> |        |
> |        |_  ///
> | 
> \ Tests (tests)
>          |
>          |_ Feature
>          |_ Unit
>          **|_ Helpers.php**
>          **|_ Pest.php**

### Composer.json

>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "../tests/"
>         }
>     },

### phpunit.xml

>     <testsuites>
>         <testsuite name="Unit">
>             <directory suffix="Test.php">../tests/Unit/*</directory>
>         </testsuite>
>         <testsuite name="Feature">
>             <directory suffix="Test.php">../tests/Feature/*</directory>
>         </testsuite>
>     </testsuites>

### Setup

PhpStorm 2020.2.2
Pest Plugin 0.4.1
Laravel 8
PHP 7.4

**Comment by olivernybroe** [comment]
@NickSdot Thanks for reporting this!

Hmm, so what changes would be needed in the command the plugin runs for this setup to work? 
Else we might be talking about making a PR to pest itself for fixing something here.

**Comment by NickSdot** [comment]
@olivernybroe I would love to come up with a specific idea. Unfortunately I don't really understand why this check even exists, because for me it seems the composer.json isn't used by PEST after. 

You are right, it's more related to PEST itself. But since PEST with command line works, I thought it would be a better idea to post it here.

**Comment by olivernybroe** [comment]
@NickSdot No problem that you created it here. 

When we figure out what exactly is going wrong, we can crosspost it. 👍

**Comment by NickSdot** [comment]
@olivernybroe so, it seems it is not only the directory structure issue, because after I fixed it, I still get another error. Anyway, step by step and first things first.

For this issue here, I would like to propose the following:
https://github.com/pestphp/pest/compare/master...NickSdot:make-root-path-working-in-subdirectory-structures

Since we already get a (correct) path from the autoloader a few lines above, I think we can leave the use of `getcwd()` behind and just count us up back to the root – as we do to get those previous parts.

What do you think?

**Comment by NickSdot** [comment]
I've created a plain repository, where you can reproduce the issue.

https://github.com/NickSdot/pest-php-subdirectory

**Comment by olivernybroe** [comment]
@NickSdot Thanks a lot. Nice with a repo to test it out on. 

Hmm looking at your diff I definitely think you are on the right track. I don't think there is a need for your fallback though as if we can't find the autoloader then the rest of the application won't work either way. 

Why is there a difference on the amount of folders to go if it is from the autoloader path?

**Comment by olivernybroe** [comment]
Btw @NickSdot could you try changing `Custom working directory` to the actual root of your project and see if it fixes it for you?
![image](https://user-images.githubusercontent.com/5870441/96117226-09885d80-0eea-11eb-9e78-c58b0020a794.png)

**Comment by NickSdot** [comment]
> Btw @NickSdot could you try changing `Custom working directory` to the actual root of your project and see if it fixes it for you?

I indeed tried this in several variations – without luck:
> /Users/username/Development/valet/projectX/
> /Users/username/Development/valet/projectX/tests/
> /Users/username/Development/valet/projectX/libraries/

**Comment by olivernybroe** [comment]
@NickSdot I just tried your example project and it was able to run the test when I changed the config like so
![image](https://user-images.githubusercontent.com/5870441/96119283-0a6ebe80-0eed-11eb-8d7b-8320a8faa61c.png)

**Comment by NickSdot** [comment]
@olivernybroe 

> I don't think there is a need for your fallback though as if we can't find the autoloader then the rest of the application won't work either way.

Correct. Removed.

> Why is there a difference on the amount of folders to go if it is from the autoloader path?

There is two cases how PEST  get the vendor path. The `$localPath` is used for tests by pest Team. 

```
    // Used when Pest is required using composer.
    $vendorPath = dirname(__DIR__, 4) . '/vendor/autoload.php';

    // Used when Pest maintainers are running Pest tests.
    $localPath = dirname(__DIR__) . '/vendor/autoload.php';
```

I had a misunderstanding what these different parts do. Today, with a more fresh mind, I got it after your comment. 

Please check the new commit. It at least fixes that the composer.json isn't found. But still, after the fix, the tests can not be found.

___

I can not get the tests for PEST itself running. 

>   PHPUnit\TextUI\Exception 
>   Please run `./vendor/bin/pest` instead of `/vendor/bin/phpunit`.

Does anyone have a hint how to make this work?

**Comment by olivernybroe** [comment]
@NickSdot So the example you gave me I cannot get it to run the tests in `/tests`.
It only wanna run tests `/libraries/tests`.

When I do `vendor/bin/pest` with CWD being `/libraries` it runs 0 tests

![image](https://user-images.githubusercontent.com/5870441/96120266-89182b80-0eee-11eb-89b5-9a699a985939.png)
Even the command for listing tests shows 0 tests.

**Comment by NickSdot** [comment]
@olivernybroe yesterday it worked for sure. Now, same as at your end; not anymore. Meanwhile I started PHPStorm new — of course.

- PEST don't run at all.
- PHPUnit runs with 0 tests.
- PEST in global test settings isn't recognized (Pest version: Not installed) and neither the executable is choosable.
- Committed changes not applied.

Apart from that, all settings are the exact same as in the project where I actually have the issue. 

There, still, PHPUnit runs by console and Storm. As well PEST there runs by console.

Very very weird, and I have no idea why the behavior changed compared to yesterday.

**Comment by olivernybroe** [comment]
@NickSdot Hmm, makes it quite hard to debug locally :( 
Let's hope your solution fixes it then and that the other guys are okay with it ;)

**Comment by olivernybroe** [comment]
As we couldn't reproduce this, I'll close 👍

**Comment by jrcii** [comment]
I installed Pest with only a default test using `pest --init`, installed the PhpStorm plugin and ran it and get:

```
Pest\Exceptions\FileOrFolderNotFound 

The file or folder with the name `composer.json` not found.

Process finished with exit code 1
```

I haven't started the possibly long/tedious process of solving this.

**Comment by olivernybroe** [comment]
@jrcii please provide reproducible steps or a project I can clone and test it out on. 
Else I can't really do much from your comment.

**Comment by j-dexx** [comment]
@olivernybroe there seems to be multiple issues in this issue now.  Locally I have my code under `/src` and I get issues, but your solution here fixes it.

> Btw @NickSdot could you try changing `Custom working directory` to the actual root of your project and see if it fixes it for you? ![image](https://user-images.githubusercontent.com/5870441/96117226-09885d80-0eea-11eb-9e78-c58b0020a794.png)
