### ISSUE TITLE
Add support for path mappings

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/pest-intellij#74]
As Windows Sub Linux is getting more and more popular, we should start supporting it. 

Phpstorm has support for the mapping of paths to sublinux however this plugin does not use the mappings. 

I wouldn't mind adding support for this, however I have no way of testing it. Any Windows user who could help out here?

**Comment by olivernybroe** [comment]
We are using paths in the following places.

## `PestRunConfigurationHandler` 
In here paths are used to define the pest executable and arguments for running pest.

## `PestNamingUtil`
We are also using paths here in `toPestTestRegex`. It is used here to generate the most optimal regex for running a single test.

## `PestLocationProvider`
It is also used in here for mapping a test to a file.

## `PestRunConfiguration`
It is also used here for working directory and executable path.

## `PestVersionDetector`
This file uses the executable to detect the pest version.


I think this was all the places that has to be updated to take path mapping in mind.

**Comment by Shhu** [comment]
Hi, 
Currently the generate path when you clic to run a specific test is something like : 
`[wsl://UBUNTU1804]:/usr/bin/php /mnt/c/dev/project/vendor/pestphp/pest/bin/pest --teamcity --configuration /mnt/c/dev/project/phpunit.xml /mnt/c/dev/project/app/Page/Tests/Feature/CreateTest.php --filter=/^P\\C:\\dev\\project\\app\\Page\\Tests\\Feature\\CreateTest::asserts\strue\sis\strue(\swith\s\(.*\)(\s#\d+)?)?$/`

**Comment by olivernybroe** [comment]
@Shhu Thanks for feedback!

Alright so looking at this command, the only path that is actually messed up is the one inside filter? 
Did you do any other changes to force it to generate correct paths for the other parts?

Does it work if you try to run tests on a whole file or a whole folder?

**Comment by Shhu** [comment]
No particular configuration done.

It works on a whole folder : 
```
/usr/bin/php /mnt/c/dev/project/vendor/pestphp/pest/bin/pest --teamcity --configuration /mnt/c/dev/project/phpunit.xml /mnt/c/dev/project/app/Page/Tests
```

It doesnt works on file but it probably a phpstorm issue (doesnt works atm on phpunit either) (i'm using 2020.2.3)
Issue : https://youtrack.jetbrains.com/issue/WI-54615
```
/usr/bin/php /mnt/c/dev/project/vendor/phpunit/phpunit/phpunit --configuration /mnt/c/dev/project/phpunit.xml --filter App\\\\Page\\\\Tests\\\\Feature\\\\CreateTest --test-suffix CreateTest.php /mnt/c/dev/project/app/Page/Tests/Feature --teamcity
```

Running a class (phpunit boilerplate) is the same as file
```
/usr/bin/php /mnt/c/dev/project/vendor/phpunit/phpunit/phpunit --configuration /mnt/c/dev/project/phpunit.xml --filter App\\\\Page\\\\Tests\\\\Feature\\\\CreateTest --test-suffix CreateTest.php /mnt/c/dev/project/app/Page/Tests/Feature --teamcity
```

**Comment by olivernybroe** [comment]
Nice!

Yeah so we let the phpunit plugin handle running a pure phpunit class.
You should however be able to run a file with pest instead of phpunit runner, but only on a pest file.

Could you try the following and see what that results in?
![image](https://user-images.githubusercontent.com/5870441/97680615-441bf980-1a97-11eb-9f37-c0cc8eed49c4.png)

**Comment by Shhu** [comment]
I dont have it on files : 
![image](https://user-images.githubusercontent.com/2306100/97687272-d4f3d480-1a99-11eb-9141-4892a922e6c9.png)
I have this on folders : 
![image](https://user-images.githubusercontent.com/2306100/97687553-e89f3b00-1a99-11eb-8500-713d11625073.png)
And on folders containing folders : 
![image](https://user-images.githubusercontent.com/2306100/97687794-f9e84780-1a99-11eb-8652-5c4f8e928e18.png)

**Comment by Shhu** [comment]
At the same time i have this  : 
![image](https://user-images.githubusercontent.com/2306100/97688526-88f55f80-1a9a-11eb-8417-980ad4bc2ed2.png)
And 
![image](https://user-images.githubusercontent.com/2306100/97688663-b8a46780-1a9a-11eb-8583-80d740fa576d.png)

**Comment by Shhu** [comment]
After creating a file with only a Pest test it works !
Apparently the phpunit boilerplate made phpstorm switch on phpunit
![image](https://user-images.githubusercontent.com/2306100/97689773-5d737480-1a9c-11eb-8c77-2fb42cbc6cef.png)

**Comment by olivernybroe** [comment]
@Shhu Awesome!

So we just have to figure out how to fix the regex so it uses the path mappings first. 

And then it looks like there is something wrong in test frameworks also for you :)

Waiting on an answer from IntelliJ on what the best approach is to deal with path mappings.

**Comment by olivernybroe** [comment]
Alright, haven't gotten an answer from them, and this has been a long time now. 

Gotta try it out myself and hope I can figure it out 👍 Will report back when I need some testing!
