### ISSUE TITLE
Missing support for extendable expects

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest-intellij#75]
The pull request https://github.com/pestphp/pest/pull/232 as been merged, and this issue is a feature request so we could have autocomplemention on extendable expects. Example:

```php
expect()->extend('toBeWithinRange', function ($min, $max) {
    return $this->toBeGreaterThanOrEqual($min)->toBeLessThanOrEqual($max);
});

test('numeric ranges', function () {
    expect(100)->toBeWithinRange(90, 110);
});
```

Note that `expect()->extend` can be the entire test suite.

**Comment by olivernybroe** [comment]
@adelf Do you see any problems with implementing this? Is this doable and so on?

**Comment by adelf** [comment]
Is there any specific place for this extending? Like, service provider?

**Comment by owenvoke** [comment]
Well, I guess it's most likely to be in `tests/Pest.php`, but I guess it'd be used in plugins too.

**Comment by nunomaduro** [comment]
The better is to scan the entire `tests` folder, for now.

**Comment by olivernybroe** [comment]
@nunomaduro how about packages, they won't have their extensions in the tests folder right? 
Meaning we would also have to lookup all files in all packages

**Comment by nunomaduro** [comment]
Ok - scan for all packages that require "pestphp/pest" on their composer files.

**Comment by olivernybroe** [comment]
Hey @adelf, I wanted to give this a go, but was hoping you could give me some pointers 👍 

So basically I need to add custom methods to the type `Expectation`, what is the best way of doing that? 😄 
For finding all of the extensions, my thoughts were to create a new indexer and store them that way. So I can just look through the index for all the methods.

**Comment by adelf** [comment]
Generated helper code (like _ide_helper.php) will be the best for users' experience, but it's hard to store fresh, and asking a user to generate it every time not good... 
So, yes. You can just build an index, collect all these methods. Just names will be enough for now I think. And then the usual completion contributor for MethodReference. There will be a warning about non-existing method, BTW...

**Comment by adelf** [comment]
BTW, seems we also need a TypeProvider for $this for lambdas inside `extend`.

**Comment by olivernybroe** [comment]
Ah yeah, so it's easier to define your extends also... 

@adelf is this a task you will be up to / have time for?

We could prob. force all plugins to have an ide helper file for now. So we "only" have to think about the extends defined in test folder. 

But is it really not possible to inject methods into a php type without using an ide helper file?
