### ISSUE TITLE
Test descriptions with parentheses not properly escaped

### ISSUE THREAD

**Issue by hackel** [pestphp/pest-intellij#76]
e.g. trying to run the following test:
```
it('has some (parentheses)')->expect(1)->toBe(1);
```
generates the following filter:
```
pest tests/Feature/ParenthesesTest.php --filter='/^P\\Tests\\Feature\\ParenthesesTest::it\shas\ssome\s(parentheses)(\swith\s\(.*\)(\s#\d+)?)?$/'
```
This is solved by simply escaping the parentheses.
```
pest tests/Feature/ParenthesesTest.php --filter='/^P\\Tests\\Feature\\ParenthesesTest::it\shas\ssome\s\(parentheses\)(\swith\s\(.*\)(\s#\d+)?)?$/'
```

**Comment by olivernybroe** [comment]
Ah nice, great catch and thanks for detailed description! 

Do you want to create a pr yourself? Else I don't mind doing it all all 👍

**Comment by hackel** [comment]
@olivernybroe I'm not a Kotlin person, I would have to set up a build environment and have no clue about testing and such.  Probably a 5 minute job for you, though!  Thanks for looking at this (minor) issue!

**Comment by olivernybroe** [comment]
@hackel No problem 👍

**Comment by olivernybroe** [comment]
This has been fixed in latest EAP release.
