### ISSUE TITLE
PhpStorm throws expression result is not used anywhere when using test() instead of it()

### ISSUE THREAD

**Issue by dingo-d** [pestphp/pest-intellij#79]
Migrated from [here](https://github.com/pestphp/pest/issues/235). 

When I use `test()` instead of `it()` my entire test gets underlined. When passing datasets to the test, the underline dissapears.

I'm on macOS 11.0.1 (BigSur), using PHP 7.4.13, and on PhpStorm 2020.3. Also, I have the pest plugin installed.

Dependency versions

```bash
pestphp/pest                                   v0.3.15            An elegant PHP Testing Framework.
pestphp/pest-plugin                            v0.3.0             The Pest plugin manager
pestphp/pest-plugin-coverage                   v0.3.0             The Pest Coverage Plugin
pestphp/pest-plugin-init                       v0.3.1             The Pest Init plugin

phpunit/php-code-coverage                      9.2.5              Library that provides collection, processing, and rendering functionality for PHP code ...
phpunit/php-file-iterator                      3.0.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                            3.1.1              Invoke callables with a timeout
phpunit/php-text-template                      2.0.4              Simple template engine.
phpunit/php-timer                              5.0.3              Utility class for timing
phpunit/phpunit                                9.5.0              The PHP Unit Testing framework.
```

The inspection gives me this

```
Expression result is not used anywhere 
Inspection info: Reports expressions that are calculated, but the calculation result is not used anywhere.
Such errors can be caused, for example, by misspelling the = operator as ==.
```

**Comment by olivernybroe** [comment]
For reference, I posted a solution in the other thread which can be used until we implement it in the plugin 
![image](https://user-images.githubusercontent.com/5870441/101465935-d938ca80-3940-11eb-82d0-a88c86a834e2.png)

For implementation guidelines (prob. for myself):
We need to add a new class which extends `InspectionSuppressor`, and add in a condition to check if it is a pest function call.

**Comment by etienneroudeix** [comment]
Gif not working above. Link to the workaround : https://github.com/pestphp/pest/issues/235#issuecomment-740440046
Thank you @olivernybroe
