### ISSUE TITLE
Mark tests as success with icon

### ISSUE THREAD

**Issue by roni-estein** [pestphp/pest-intellij#88]
Hey Oliver,

Would be cool if we could mark completed tests with checks. 
<img width="286" alt="Screen Shot 2021-01-05 at 11 01 34 PM" src="https://user-images.githubusercontent.com/8517475/103731091-f85f6200-4fa9-11eb-895c-c34bb6c1a1fe.png">

As I'm converting tests over, I realized I was looking for them.
<img width="487" alt="Screen Shot 2021-01-05 at 10 58 59 PM" src="https://user-images.githubusercontent.com/8517475/103731066-e7aeec00-4fa9-11eb-9233-764b0a49457b.png">

**Comment by olivernybroe** [comment]
Duplicate :)

**Comment by roni-estein** [comment]
ohh sorry my search-fu was not strong enough! Humble apologies master ;)

**Comment by roni-estein** [comment]
ouch I duplicated it! I must need more coffee!
