### ISSUE TITLE
Mark passing and failing tests.

### ISSUE THREAD

**Issue by roni-estein** [pestphp/pest-intellij#89]
Hey Oliver,

Would be cool if we could mark completed tests with checks. 
<img width="487" alt="Screen Shot 2021-01-05 at 10 58 59 PM" src="https://user-images.githubusercontent.com/8517475/103731066-e7aeec00-4fa9-11eb-9233-764b0a49457b.png">

As I'm converting tests over, I realized I was looking for them.
<img width="286" alt="Screen Shot 2021-01-05 at 11 01 34 PM" src="https://user-images.githubusercontent.com/8517475/103731091-f85f6200-4fa9-11eb-895c-c34bb6c1a1fe.png">

**Comment by olivernybroe** [comment]
Maybe we could get cool custom icons for this? @caneco 🥇

**Comment by olivernybroe** [comment]
Ho @roni-estein,

I have created a first implementation of this, would you be willing to test it out?
[PEST PHP-0.4.3-EAP.2.zip](https://github.com/pestphp/pest-intellij/files/6114113/PEST.PHP-0.4.3-EAP.2.zip)

**Comment by jeremynikolic** [comment]
Oliver,
I've given this a test and could not see the new icons. 
The double blue arrow also went back to default phpunit icon.

Here are a few screenshots:
Pest test stays like this weither I run it or not, and weither it fails or succeed
`php /var/www/.../vendor/bin/pest --teamcity --configuration /var/www/.../phpunit.xml /var/www/.../tests/Unit/DummyPestTest.php`
![image](https://user-images.githubusercontent.com/4478969/110602891-b6f45a00-8186-11eb-8082-985c6db45889.png)

Gave phpunit test a go in case my setup was having issues and it behaves normally
`php /var/www/.../vendor/phpunit/phpunit/phpunit --configuration /var/www/.../phpunit.xml --filter DummyPHPUnitTest --test-suffix DummyPHPUnitTest.php /var/www/.../tests/Unit --teamcity`
![image](https://user-images.githubusercontent.com/4478969/110602911-bd82d180-8186-11eb-813b-3634baa4b4ab.png)


PhpStorm 2021.1 EAP + PEST PHP-0.4.3-EAP.2
PHP is a remote interpreter pointing to a docker

**Comment by olivernybroe** [comment]
Thanks @jeremynikolic 👍 

The icons are back to phpstorms defaults, because we are missing icons for failing and passing tests, right now we only have icons for running a test 😄 

The other issue is def. because or remote interpreter, this is the standard path mapping issue. I'll see if I can somehow get the right context, as the issue here is that it doesn't know if you had run the test with a remote interpreter or a local one.

**Comment by olivernybroe** [comment]
Got a new version available for testing out. 👍 
Hopefully this should fix the problem so the icons change correctly now.

[PEST PHP-0.4.3-EAP.2.zip](https://github.com/pestphp/pest-intellij/files/6115133/PEST.PHP-0.4.3-EAP.2.zip)

**Comment by jeremynikolic** [comment]
Gave this another go, still with the docker interpreter, no luck so far. The results are the same as with previous version.

Are there more infos I could extract from my setup which could help ?

**Comment by olivernybroe** [comment]
@jeremynikolic How is your docker setup created?
When I test it out with docker it seems to work, this is my setup.
![image](https://user-images.githubusercontent.com/5870441/110630891-3f362780-81a6-11eb-8c6c-6a3e28dbfb4c.png)
![image](https://user-images.githubusercontent.com/5870441/110630930-4cebad00-81a6-11eb-9cd4-fd8b8fc7ba73.png)

Resulting in my command looking the following way
![image](https://user-images.githubusercontent.com/5870441/110631049-6856b800-81a6-11eb-9816-572a808aecbd.png)
And giving me the correct icons
![image](https://user-images.githubusercontent.com/5870441/110631160-845a5980-81a6-11eb-87f0-672db4c90c41.png)

**Comment by olivernybroe** [comment]
So @caneco for this one we are actually needs multiple icons. 

We need a passing and failing icon with a single tick 👍 (as we are going to use the ones with double ticks for running the whole file)

So basically something like this
![image](https://user-images.githubusercontent.com/5870441/110644563-84158a80-81b5-11eb-924a-1431ea61229e.png)
and then have an edition for when a test is passed and for when a test fails. (this is how phpstorm built-in icons looks like)
![image](https://user-images.githubusercontent.com/5870441/110644732-af987500-81b5-11eb-8fa9-ae04de393e9d.png)
![image](https://user-images.githubusercontent.com/5870441/110644920-d9ea3280-81b5-11eb-960d-d9fab77613a6.png)

**Comment by olivernybroe** [comment]
As @jeremynikolic got it working (I sent him a wrong version my bad...) I'll mark this as completed and do a EAP release. 👍

**Comment by roni-estein** [comment]
Nice work, just in the middle of a never-ending sprint, squashing tiny front end bugs, but I'll install and run this in the morning! Thanks! Sorry I didn't see this message before.

**Comment by olivernybroe** [comment]
@roni-estein no worries, this all went pretty fast also 👍
